
import type { Site, Artifact } from '@/types';

const allArtifacts: Artifact[] = [
  {
    id: 'art-1',
    siteId: 'site-1',
    title: {
      en: 'Mughal Miniature Painting',
      hi: 'मुगल लघु चित्रकला',
      kn: 'ಮೊಘಲ್ ಸೂಕ್ಷ್ಮಚಿತ್ರ',
      or: 'ମୋଗଲ କ୍ଷୁଦ୍ର ଚିତ୍ର',
    },
    description: {
      en: 'This exquisite Mughal miniature painting is a hallmark of a rich artistic tradition that flourished under the Mughal Empire from the 16th to the 19th century. These small, highly detailed paintings were often created for books and albums, serving as intimate works of art. Characterized by their delicate brushwork, vibrant mineral-based colors, and complex compositions, they frequently depicted courtly life, historical events, literary scenes, and portraits of royalty. The level of detail is so fine that it often requires a magnifying glass to fully appreciate the artists skill in rendering textures, expressions, and ornamentation.',
      hi: 'यह उत्कृष्ट मुगल लघु चित्रकला एक समृद्ध कलात्मक परंपरा का प्रतीक है जो 16वीं से 19वीं शताब्दी तक मुगल साम्राज्य के अधीन फली-फूली। ये छोटी, अत्यधिक विस्तृत पेंटिंग अक्सर किताबों और एल्बमों के लिए बनाई जाती थीं, जो कला के अंतरंग कार्यों के रूप में काम करती थीं। अपनी नाजुक ब्रशवर्क, जीवंत खनिज-आधारित रंगों और जटिल रचनाओं की विशेषता के लिए, वे अक्सर दरबारी जीवन, ऐतिहासिक घटनाओं, साहित्यिक दृश्यों और राजघरानों के चित्रों को दर्शाती थीं। विवरण का स्तर इतना सूक्ष्म है कि बनावट, भाव और अलंकरण को प्रस्तुत करने में कलाकारों के कौशल की पूरी तरह से सराहना करने के लिए अक्सर एक आवर्धक कांच की आवश्यकता होती है।',
      kn: 'ಈ ಸೊಗಸಾದ ಮೊಘಲ್ ಚಿಕಣಿ ಚಿತ್ರಕಲೆಯು 16 ರಿಂದ 19 ನೇ ಶತಮಾನದವರೆಗೆ ಮೊಘಲ್ ಸಾಮ್ರಾಜ್ಯದ ಅಡಿಯಲ್ಲಿ ಪ್ರವರ್ಧಮಾನಕ್ಕೆ ಬಂದ ಶ್ರೀಮಂತ ಕಲಾತ್ಮಕ ಸಂಪ್ರದಾಯದ ಒಂದು ವಿಶಿಷ್ಟ ಲಕ್ಷಣವಾಗಿದೆ. ಈ ಸಣ್ಣ, ಹೆಚ್ಚು ವಿವರವಾದ ವರ್ಣಚಿತ್ರಗಳನ್ನು ಹೆಚ್ಚಾಗಿ ಪುಸ್ತಕಗಳು ಮತ್ತು ಆಲ್ಬಮ್‌ಗಳಿಗಾಗಿ ರಚಿಸಲಾಗಿದೆ, ಇದು ಕಲೆಯ ನಿಕಟ ಕೃತಿಗಳಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ. ತಮ್ಮ ಸೂಕ್ಷ್ಮವಾದ ಕುಂಚ ಕೆಲಸ, ರೋಮಾಂಚಕ ಖನಿಜ ಆಧಾರಿತ ಬಣ್ಣಗಳು ಮತ್ತು ಸಂಕೀರ್ಣ ಸಂಯೋಜನೆಗಳಿಂದ ನಿರೂಪಿಸಲ್ಪಟ್ಟಿದೆ, ಅವರು ಆಗಾಗ್ಗೆ ಆಸ್ಥಾನಿಕ ಜೀವನ, ಐತಿಹಾಸಿಕ ಘಟನೆಗಳು, ಸಾಹಿತ್ಯಿಕ ದೃಶ್ಯಗಳು ಮತ್ತು ರಾಜಮನೆತನದ ಭಾವಚಿತ್ರಗಳನ್ನು ಚಿತ್ರಿಸಿದ್ದಾರೆ. ವಿವರಗಳ ಮಟ್ಟವು ತುಂಬಾ ಉತ್ತಮವಾಗಿದೆ, ಟೆಕಶ್ಚರ್, ಅಭಿವ್ಯಕ್ತಿಗಳು ಮತ್ತು ಅಲಂಕರಣವನ್ನು ನಿರೂಪಿಸುವಲ್ಲಿ ಕಲಾವಿದರ ಕೌಶಲ್ಯವನ್ನು ಸಂಪೂರ್ಣವಾಗಿ ಪ್ರಶಂಸಿಸಲು ಭೂತಗನ್ನಡಿಯ ಅಗತ್ಯವಿರುತ್ತದೆ.',
      or: 'ଏହି ઉત્କୃଷ୍ଟ ମୋଗଲ କ୍ଷୁଦ୍ର ଚିତ୍ର ଏକ ସମୃଦ୍ଧ କଳାତ୍ମକ ପରମ୍ପରାର ଏକ ବିଶେଷତ୍ୱ ଅଟେ ଯାହା ୧୬ଶରୁ ୧୯ଶ ଶତାବ୍ଦୀ ପର୍ଯ୍ୟନ୍ତ ମୋଗଲ ସାମ୍ରାଜ୍ୟ ଅଧୀନରେ ବୃଦ୍ଧି ପାଇଥିଲା। ଏହି ଛୋଟ, ଅତ୍ୟଧିକ ବିସ୍ତୃତ ଚିତ୍ରଗୁଡ଼ିକ ପ୍ରାୟତଃ ପୁସ୍ତକ ଏବଂ ଆଲବମ୍ ପାଇଁ ସୃଷ୍ଟି କରାଯାଇଥିଲା, ଯାହା କଳାର ଅନ୍ତରଙ୍ଗ କାର୍ଯ୍ୟ ଭାବରେ କାର୍ଯ୍ୟ କରୁଥିଲା। ସେମାନଙ୍କର ସୂକ୍ଷ୍ମ ବ୍ରଶ୍ କାର୍ଯ୍ୟ, ଜୀବନ୍ତ ଖଣିଜ-ଆଧାରିତ ରଙ୍ଗ ଏବଂ ଜଟିଳ ରଚନା ଦ୍ୱାରା ବର୍ଣ୍ଣିତ, ସେମାନେ ବାରମ୍ବାର ଦରବାରୀ ଜୀବନ, ଐତିହାସିକ ଘଟଣା, ସାହିତ୍ୟିକ ଦୃଶ୍ୟ ଏବଂ ରାଜକୀୟତାର ଚିତ୍ର ଦେଖାଉଥିଲେ। ବିବରଣୀର ସ୍ତର ଏତେ ସୂକ୍ଷ୍ମ ଯେ ଏହା ପ୍ରାୟତଃ ଗଠନ, ଅଭିବ୍ୟକ୍ତି ଏବଂ ଅଳଙ୍କାର ପ୍ରଦାନରେ କଳାକାରଙ୍କ ଦକ୍ଷତାକୁ ସମ୍ପୂର୍ଣ୍ଣ ରୂପେ ପ୍ରଶଂସା କରିବା ପାଇଁ ଏକ ବର୍ଦ୍ଧକ କାଚ ଆବଶ୍ୟକ କରେ।',
    },
    imageUrlId: 'mughal-painting-artifact',
    modelFileUrl: '/models/mughal_painting.glb',
    lowPolyModelUrl: '/models/mughal_painting_low.glb',
    fallbackImageUrlId: 'mughal-painting-artifact',
    arLink: 'https://arvr.google.com/scene-viewer/1.0?file=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF/DamagedHelmet.gltf',
  },
  {
    id: 'art-2',
    siteId: 'site-2',
    title: {
      en: 'Vijayanagara Coin',
      hi: 'विजयनगर सिक्का',
      kn: 'ವಿಜಯನಗರ ನಾಣ್ಯ',
      or: 'ବିଜୟନଗର ମୁଦ୍ରା',
    },
    description: {
      en: 'This gold coin is a remarkable artifact from the prosperous Vijayanagara Empire, which dominated South India from the 14th to the 17th century. The empire was known for its robust economy and extensive trade, reflected in its high-quality currency. These coins, known as "Varahas," typically feature intricate engravings of Hindu deities like Vishnu or his avatars, powerful animals such as bulls or elephants, or the Gandaberunda, a mythical two-headed bird symbolizing royal power. Each coin is not just a piece of currency but a miniature work of art, telling a story of the empire\'s devotion, wealth, and sophisticated metallurgical skills during its golden age.',
      hi: 'यह सोने का सिक्का समृद्ध विजयनगर साम्राज्य का एक उल्लेखनीय कलाकृति है, जिसने 14वीं से 17वीं शताब्दी तक दक्षिण भारत पर प्रभुत्व जमाया। साम्राज्य अपनी मजबूत अर्थव्यवस्था और व्यापक व्यापार के लिए जाना जाता था, जो इसकी उच्च गुणवत्ता वाली मुद्रा में परिलक्षित होता है। इन सिक्कों को "वराह" के रूप में जाना जाता है, जिनमें आमतौर पर विष्णु या उनके अवतारों जैसे हिंदू देवताओं, बैल या हाथी जैसे शक्तिशाली जानवरों, या शाही शक्ति का प्रतीक एक पौराणिक दो सिरों वाले पक्षी गंडबेरुंड की जटिल नक्काशी होती है। प्रत्येक सिक्का केवल मुद्रा का एक टुकड़ा नहीं है, बल्कि कला का एक लघु काम है, जो अपने स्वर्ण युग के दौरान साम्राज्य की भक्ति, धन और परिष्कृत धातुकर्म कौशल की कहानी कहता है।',
      kn: 'ಈ ಚಿನ್ನದ ನಾಣ್ಯವು 14 ರಿಂದ 17 ನೇ ಶತಮಾನದವರೆಗೆ ದಕ್ಷಿಣ ಭಾರತದಲ್ಲಿ ಪ್ರಾಬಲ್ಯ ಹೊಂದಿದ್ದ ಸಮೃದ್ಧ ವಿಜಯನಗರ ಸಾಮ್ರಾಜ್ಯದ ಗಮನಾರ್ಹ ಕಲಾಕೃತಿಯಾಗಿದೆ. ಸಾಮ್ರಾಜ್ಯವು ತನ್ನ ದೃಢವಾದ ಆರ್ಥಿಕತೆ ಮತ್ತು ವ್ಯಾಪಕವಾದ ವ್ಯಾಪಾರಕ್ಕೆ ಹೆಸರುವಾಸಿಯಾಗಿದೆ, ಅದರ ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಕರೆನ್ಸಿಯಲ್ಲಿ ಪ್ರತಿಫಲಿಸುತ್ತದೆ. "ವರಾಹಗಳು" ಎಂದು ಕರೆಯಲ್ಪಡುವ ಈ ನಾಣ್ಯಗಳು, ವಿಷ್ಣು ಅಥವಾ ಅವನ ಅವತಾರಗಳಂತಹ ಹಿಂದೂ ದೇವತೆಗಳ ಸಂಕೀರ್ಣವಾದ ಕೆತ್ತನೆಗಳನ್ನು, ಗೂಳಿಗಳು ಅಥವಾ ಆನೆಗಳಂತಹ ಶಕ್ತಿಯುತ ಪ್ರಾಣಿಗಳನ್ನು, ಅಥವಾ ರಾಜ ಶಕ್ತಿಯನ್ನು ಸಂಕೇತಿಸುವ ಪೌರಾಣಿಕ ಎರಡು ತಲೆಯ ಹಕ್ಕಿಯಾದ ಗಂಡಭೇರುಂಡವನ್ನು ಒಳಗೊಂಡಿರುತ್ತವೆ. ಪ್ರತಿಯೊಂದು ನಾಣ್ಯವು ಕೇವಲ ಕರೆನ್ಸಿಯ ತುಣುಕಲ್ಲ, ಆದರೆ ಕಲೆಯ ಒಂದು ಚಿಕಣಿ ಕೃತಿಯಾಗಿದೆ, ಇದು ತನ್ನ ಸುವರ್ಣ ಯುಗದಲ್ಲಿ ಸಾಮ್ರಾಜ್ಯದ ಭಕ್ತಿ, ಸಂಪತ್ತು ಮತ್ತು ಅತ್ಯಾಧುನಿಕ ಲೋಹಶಾಸ್ತ್ರದ ಕೌಶಲ್ಯಗಳ ಕಥೆಯನ್ನು ಹೇಳುತ್ತದೆ.',
      or: 'ଏହି ସୁନା ମୁଦ୍ରା ୧୪ରୁ ୧୭ଶ ଶତାବ୍ଦୀ ପର୍ଯ୍ୟନ୍ତ ଦକ୍ଷିଣ ଭାରତରେ ପ୍ରାଧାନ୍ୟ ବିସ୍ତାର କରିଥିବା ସମୃଦ୍ଧ ବିଜୟନଗର ସାମ୍ରାଜ୍ୟର ଏକ ଉଲ୍ଲେଖନୀୟ କଳାକୃତି। ସାମ୍ରାଜ୍ୟ ଏହାର ସୁଦୃଢ଼ ଅର୍ଥନୀତି ଏବଂ ବ୍ୟାପକ ବାଣିଜ୍ୟ ପାଇଁ ଜଣାଶୁଣା ଥିଲା, ଯାହା ଏହାର ଉଚ୍ଚମାନର ମୁଦ୍ରାରେ ପ୍ରତିଫଳିତ ହୋଇଥିଲା। "ବରାହ" ଭାବରେ ଜଣାଶୁଣା ଏହି ମୁଦ୍ରାଗୁଡ଼ିକରେ ସାଧାରଣତଃ ବିଷ୍ଣୁ କିମ୍ବା ତାଙ୍କ ଅବତାରଙ୍କ ପରି ହିନ୍ଦୁ ଦେବତା, ଷଣ୍ଢ କିମ୍ବା ହାତୀ ପରି ଶକ୍ତିଶାଳୀ ପଶୁ, କିମ୍ବା ଗଣ୍ଡବେରୁଣ୍ଡ, ରାଜକୀୟ ଶକ୍ତିର ପ୍ରତୀକ ଏକ ପୌରାଣିକ ଦୁଇ-ମୁଣ୍ଡିଆ ପକ୍ଷୀର ଜଟିଳ ଖୋଦେଇ ଦେଖାଯାଏ। ପ୍ରତ୍ୟେକ ମୁଦ୍ରା କେବଳ ମୁଦ୍ରାର ଏକ ଅଂଶ ନୁହେଁ, ବରଂ କଳାର ଏକ କ୍ଷୁଦ୍ର କାର୍ଯ୍ୟ, ଯାହା ଏହାର ସ୍ୱର୍ଣ୍ଣିମ ଯୁଗରେ ସାମ୍ରାଜ୍ୟର ଭକ୍ତି, ସମ୍ପଦ ଏବଂ ଅତ୍ୟାଧୁନିକ ଧାତୁ କୌଶଳର କାହାଣୀ କହେ।',
    },
    imageUrlId: 'vijayanagara-coin-artifact',
    modelFileUrl: '/models/vijayanagara_coin.glb',
    lowPolyModelUrl: '/models/vijayanagara_coin_low.glb',
    fallbackImageUrlId: 'vijayanagara-coin-artifact',
  },
  {
    id: 'art-3',
    siteId: 'site-3',
    title: {
      en: 'Iron Pillar Inscription',
      hi: 'लौह स्तंभ शिलालेख',
      kn: 'ಕಬ್ಬಿಣದ ಸ್ತಂಭದ ಶಿಲಾಶಾಸನ',
      or: 'ଲୌହ ସ୍ତମ୍ଭ ଅଭିଲେଖ',
    },
    description: {
      en: 'This inscription is a testament to the advanced metallurgical knowledge of ancient India. Located in the Qutub Minar complex in Delhi, the Iron Pillar stands as a marvel of engineering, having famously resisted corrosion for over 1,600 years. The Sanskrit text, written in the Brahmi script, is dedicated to the Hindu deity Vishnu and honors a powerful king, often identified as Chandragupta II of the Gupta dynasty. The pillar\'s composition—98% pure wrought iron—and the unique passive protective film on its surface have baffled scientists for centuries, making it a globally significant artifact of materials science and a symbol of India\'s rich scientific heritage.',
      hi: 'यह शिलालेख प्राचीन भारत के उन्नत धातुकर्म ज्ञान का प्रमाण है। दिल्ली के कुतुब मीनार परिसर में स्थित, लौह स्तंभ इंजीनियरिंग के एक चमत्कार के रूप में खड़ा है, जो 1,600 से अधिक वर्षों से जंग का सफलतापूर्वक प्रतिरोध कर रहा है। ब्राह्मी लिपि में लिखा गया संस्कृत पाठ, हिंदू देवता विष्णु को समर्पित है और एक शक्तिशाली राजा का सम्मान करता है, जिसे अक्सर गुप्त वंश के चंद्रगुप्त द्वितीय के रूप में पहचाना जाता है। स्तंभ की संरचना—98% शुद्ध गढ़ा लोहा—और इसकी सतह पर अद्वितीय निष्क्रिय सुरक्षात्मक फिल्म ने वैज्ञानिकों को सदियों से चकित किया है, जो इसे पदार्थ विज्ञान का विश्व स्तर पर महत्वपूर्ण कलाकृति और भारत की समृद्ध वैज्ञानिक विरासत का प्रतीक बनाता है।',
      kn: 'ಈ ಶಾಸನವು ಪ್ರಾಚೀನ ಭಾರತದ ಮುಂದುವರಿದ ಲೋಹಶಾಸ್ತ್ರದ ಜ್ಞಾನಕ್ಕೆ ಸಾಕ್ಷಿಯಾಗಿದೆ. ದೆಹಲಿಯ ಕುತುಬ್ ಮಿನಾರ್ ಸಂಕೀರ್ಣದಲ್ಲಿ ನೆಲೆಗೊಂಡಿರುವ ಕಬ್ಬಿಣದ ಸ್ತಂಭವು ಇಂಜಿನಿಯರಿಂಗ್‌ನ ಅದ್ಭುತವಾಗಿ ನಿಂತಿದೆ, ಇದು 1,600 ವರ್ಷಗಳಿಂದ ತುಕ್ಕು ಹಿಡಿಯುವುದನ್ನು ಯಶಸ್ವಿಯಾಗಿ ವಿರೋಧಿಸಿದೆ. ಬ್ರಾಹ್ಮಿ ಲಿಪಿಯಲ್ಲಿ ಬರೆಯಲಾದ ಸಂಸ್ಕೃತ ಪಠ್ಯವು ಹಿಂದೂ ದೇವತೆಯಾದ ವಿಷ್ಣುವಿಗೆ ಸಮರ್ಪಿತವಾಗಿದೆ ಮತ್ತು ಗುಪ್ತ ರಾಜವಂಶದ ಚಂದ್ರಗುಪ್ತ II ಎಂದು ಗುರುತಿಸಲ್ಪಟ್ಟ ಪ್ರಬಲ ರಾಜನನ್ನು ಗೌರವಿಸುತ್ತದೆ. ಸ್ತಂಭದ ಸಂಯೋಜನೆ-98% ಶುದ್ಧ ಮೆತು ಕಬ್ಬಿಣ-ಮತ್ತು ಅದರ ಮೇಲ್ಮೈಯಲ್ಲಿರುವ ವಿಶಿಷ್ಟವಾದ ನಿಷ್ಕ್ರಿಯ ರಕ್ಷಣಾತ್ಮಕ ಫಿಲ್ಮ್ ವಿಜ್ಞಾನಿಗಳನ್ನು ಶತಮಾನಗಳಿಂದ ದಿಗ್ಭ್ರಮೆಗೊಳಿಸಿದೆ, ಇದು ವಸ್ತು ವಿಜ್ಞಾನದ ಜಾಗತಿಕವಾಗಿ ಮಹತ್ವದ ಕಲಾಕೃತಿಯಾಗಿದೆ ಮತ್ತು ಭಾರತದ ಶ್ರೀಮಂತ ವೈಜ್ಞಾನಿಕ ಪರಂಪರೆಯ ಸಂಕೇತವಾಗಿದೆ.',
      or: 'ଏହି ଶିଳାଲିପି ପ୍ରାଚୀନ ଭାରତର ଉନ୍ନତ ଧାତୁ ବିଜ୍ଞାନର ଏକ ପ୍ରମାଣ। ଦିଲ୍ଲୀର କୁତୁବ ମିନାର ପରିସରରେ ଅବସ୍ଥିତ, ଲୌହ ସ୍ତମ୍ଭ ଇଞ୍ଜିନିୟରିଂର ଏକ ଚମତ୍କାର ଭାବରେ ଛିଡା ହୋଇଛି, ଯାହା ୧,୬୦୦ ବର୍ଷରୁ ଅଧିକ ସମୟ ଧରି କ୍ଷୟକୁ ସଫଳତାର ସହ ପ୍ରତିରୋଧ କରିଆସୁଛି। ବ୍ରାହ୍ମୀ ଲିପିରେ ଲିଖିତ ସଂସ୍କୃତ ପାଠ୍ୟ, ହିନ୍ଦୁ ଦେବତା ବିଷ୍ଣୁଙ୍କୁ ସମର୍ପିତ ଏବଂ ଜଣେ ଶକ୍ତିଶାଳୀ ରାଜାଙ୍କୁ ସମ୍ମାନିତ କରେ, ଯାହାଙ୍କୁ ପ୍ରାୟତଃ ଗୁପ୍ତ ରାଜବଂଶର ଚନ୍ଦ୍ରଗୁପ୍ତ ଦ୍ୱିତୀୟ ବୋଲି ଚିହ୍ନଟ କରାଯାଏ। ସ୍ତମ୍ଭର ଗଠନ—୯୮% ଶୁଦ୍ଧ ଗଢ଼ା ଲୁହା—ଏବଂ ଏହାର ପୃଷ୍ଠରେ ଥିବା ଅନନ୍ୟ ନିଷ୍କ୍ରିୟ ସୁରକ୍ଷା ଫିଲ୍ମ ବୈଜ୍ଞାନିକମାନଙ୍କୁ ଶତାବ୍ଦୀ ଧରି ଆଶ୍ଚର୍ଯ୍ୟ କରିଛି, ଯାହା ଏହାକୁ ପଦାର୍ଥ ବିଜ୍ଞାନର ବିଶ୍ୱ ସ୍ତରରେ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ କଳାକୃତି ଏବଂ ଭାରତର ସମୃଦ୍ଧ ବୈଜ୍ଞାନିକ ପରମ୍ପରାର ପ୍ରତୀକ କରିଛି।',
    },
    imageUrlId: 'iron-pillar-artifact',
    modelFileUrl: '/models/iron_pillar_inscription.glb',
    lowPolyModelUrl: '/models/iron_pillar_inscription_low.glb',
    fallbackImageUrlId: 'iron-pillar-artifact',
  },
  {
    id: 'art-4',
    siteId: 'site-2',
    title: {
      en: 'Lakshmi Narasimha Statue',
      hi: 'लक्ष्मी नरसिम्हा प्रतिमा',
      kn: 'ಲಕ್ಷ್ಮಿ ನರಸಿಂಹ ಪ್ರತಿಮೆ',
      or: 'ଲକ୍ଷ୍ମୀ ନରସିଂହ ପ୍ରତିମୂର୍ତ୍ତି',
    },
    description: {
      en: 'This colossal monolithic statue, located in the historic ruins of Hampi, represents Lakshmi Narasimha, the fierce man-lion avatar of the Hindu god Vishnu. Carved in 1528 AD during the reign of King Krishnadevaraya, it stands as one of the most imposing sculptures of the Vijayanagara Empire. The deity is depicted seated in a cross-legged yogic posture, with the Goddess Lakshmi on his lap, although her figure is now largely damaged. The raw power conveyed by Narasimha\'s bulging eyes and fierce expression is a testament to the masterful artistry and deep religious devotion that characterized this powerful South Indian empire.',
      hi: 'हम्पी के ऐतिहासिक खंडहरों में स्थित यह विशाल एकाश्मक प्रतिमा, हिंदू देवता विष्णु के उग्र पुरुष-सिंह अवतार लक्ष्मी नरसिंह का प्रतिनिधित्व करती है। 1528 ईस्वी में राजा कृष्णदेवराय के शासनकाल के दौरान तराशी गई, यह विजयनगर साम्राज्य की सबसे भव्य मूर्तियों में से एक के रूप में खड़ी है। देवता को पद्मासन में बैठे हुए दर्शाया गया है, उनकी गोद में देवी लक्ष्मी हैं, हालांकि उनकी आकृति अब काफी हद तक क्षतिग्रस्त हो गई है। नरसिंह की उभरी हुई आँखों और उग्र अभिव्यक्ति द्वारा व्यक्त की गई कच्ची शक्ति, इस शक्तिशाली दक्षिण भारतीय साम्राज्य की विशेषता वाली उत्कृष्ट कलात्मकता और गहरी धार्मिक भक्ति का प्रमाण है।',
      kn: 'ಹಂಪಿಯ ಐತಿಹಾಸಿಕ ಅವಶೇಷಗಳಲ್ಲಿ ನೆಲೆಗೊಂಡಿರುವ ಈ ಬೃಹತ್ ಏಕಶಿಲಾ ಪ್ರತಿಮೆಯು ಹಿಂದೂ ದೇವರಾದ ವಿಷ್ಣುವಿನ ಉಗ್ರ ನರ-ಸಿಂಹ ಅವತಾರವಾದ ಲಕ್ಷ್ಮಿ ನರಸಿಂಹನನ್ನು ಪ್ರತಿನಿಧಿಸುತ್ತದೆ. 1528 AD ಯಲ್ಲಿ ರಾಜ ಕೃಷ್ಣದೇವರಾಯನ ಆಳ್ವಿಕೆಯಲ್ಲಿ ಕೆತ್ತಲಾಗಿದೆ, ಇದು ವಿಜಯನಗರ ಸಾಮ್ರಾಜ್ಯದ ಅತ್ಯಂತ ಭವ್ಯವಾದ ಶಿಲ್ಪಗಳಲ್ಲಿ ಒಂದಾಗಿದೆ. ದೇವತೆಯನ್ನು ಅಡ್ಡ-ಕಾಲಿನ ಯೋಗ ಭಂಗಿಯಲ್ಲಿ ಕುಳಿತಿರುವುದನ್ನು ಚಿತ್ರಿಸಲಾಗಿದೆ, ಅವನ ಮಡಿಲಲ್ಲಿ ಲಕ್ಷ್ಮಿ ದೇವತೆ ಇದ್ದಾಳೆ, ಆದರೂ ಅವಳ ಆಕೃತಿ ಈಗ ಹೆಚ್ಚಾಗಿ ಹಾನಿಯಾಗಿದೆ. ನರಸಿಂಹನ ಉಬ್ಬುವ ಕಣ್ಣುಗಳು ಮತ್ತು ಉಗ್ರ ಅಭಿವ್ಯಕ್ತಿಯಿಂದ ತಿಳಿಸುವ ಕಚ್ಚಾ ಶಕ್ತಿಯು ಈ ಪ್ರಬಲ ದಕ್ಷಿಣ ಭಾರತದ ಸಾಮ್ರಾಜ್ಯವನ್ನು ನಿರೂಪಿಸುವ ನಿಪುಣ ಕಲಾತ್ಮಕತೆ ಮತ್ತು ಆಳವಾದ ಧಾರ್ಮಿಕ ಭಕ್ತಿಗೆ ಸಾಕ್ಷಿಯಾಗಿದೆ.',
      or: 'ହାମ୍ପିର ଐତିହାସିକ ଧ୍ୱଂସାବଶେଷରେ ଅବସ୍ଥିତ ଏହି ବିଶାଳ ଏକଶିଳା ପ୍ରତିମୂର୍ତ୍ତି, ହିନ୍ଦୁ ଦେବତା ବିଷ୍ଣୁଙ୍କ ଉଗ୍ର ମାନବ-ସିଂହ ଅବତାର ଲକ୍ଷ୍ମୀ ନରସିଂହଙ୍କୁ ପ୍ରତିନିଧିତ୍ୱ କରେ। ୧୫୨୮ ଖ୍ରୀଷ୍ଟାବ୍ଦରେ ରାଜା କୃଷ୍ଣଦେବରାୟଙ୍କ ଶାସନ କାଳରେ ଖୋଦିତ, ଏହା ବିଜୟନଗର ସାମ୍ରାଜ୍ୟର ସବୁଠାରୁ ପ୍ରଭାବଶାଳୀ ମୂର୍ତ୍ତି ମଧ୍ୟରୁ ଗୋଟିଏ ଭାବରେ ଛିଡା ହୋଇଛି। ଦେବତାଙ୍କୁ ଏକ କ୍ରସ୍-ଲେଗ୍ ଯୋଗ ଭଙ୍gimeରେ ବସିଥିବାର ଚିତ୍ରଣ କରାଯାଇଛି, ତାଙ୍କ କୋଳରେ ଦେବୀ ଲକ୍ଷ୍ମୀ ଅଛନ୍ତି, ଯଦିଓ ତାଙ୍କର ଆକୃତି ବର୍ତ୍ତମାନ ବହୁ ପରିମାଣରେ କ୍ଷତିଗ୍ରସ୍ତ ହୋଇଛି। ନରସିଂହଙ୍କ ଉନ୍ମୁକ୍ତ ଆଖି ଏବଂ ଉଗ୍ର ଅଭିବ୍ୟକ୍ତି ଦ୍ୱାରା ପ୍ରକାଶିତ କଞ୍ଚା ଶକ୍ତି, ଏହି ଶକ୍ତିଶାଳୀ ଦକ୍ଷିଣ ଭାରତୀୟ ସାମ୍ରାଜ୍ୟକୁ ବର୍ଣ୍ଣନା କରୁଥିବା ନିପୁଣ କଳାକାରିତା ଏବଂ ଗଭୀର ଧାର୍ମିକ ଭକ୍ତିର ଏକ ପ୍ରମାଣ।',
    },
    imageUrlId: 'lakshmi-narasimha-artifact',
    modelFileUrl: '/models/lakshmi_narasimha.glb',
    lowPolyModelUrl: '/models/lakshmi_narasimha_low.glb',
    fallbackImageUrlId: 'lakshmi-narasimha-artifact',
  },
  {
    id: 'art-5',
    siteId: 'site-2',
    title: {
      en: 'Harihara Statue',
      hi: 'हरिहर प्रतिमा',
      kn: 'ಹರಿಹರ ಪ್ರತಿಮೆ',
      or: 'ହରିହର ପ୍ରତିମୂର୍ତ୍ତି',
    },
    description: {
      en: 'This remarkable statue embodies the composite Hindu deity Harihara, a powerful symbol of unity representing the fusion of Vishnu (Hari) and Shiva (Hara). This form illustrates the philosophical concept that these two major gods are different aspects of the one ultimate reality, Brahman. Typically, one half of the statue displays Shiva\'s attributes, such as the trident and matted hair, while the other half shows Vishnu\'s emblems like the conch and discus. Such artifacts are culturally significant as they reflect the syncretic nature of Hinduism and the historical efforts to harmonize the Vaishnavite and Shaivite traditions, promoting tolerance and unity among different sects.',
      hi: 'यह उल्लेखनीय प्रतिमा समग्र हिंदू देवता हरिहर का प्रतीक है, जो विष्णु (हरि) और शिव (हर) के संलयन का प्रतिनिधित्व करने वाली एकता का एक शक्तिशाली प्रतीक है। यह रूप इस दार्शनिक अवधारणा को दर्शाता है कि ये दो प्रमुख देवता एक अंतिम वास्तविकता, ब्रह्म के विभिन्न पहलू हैं। आमतौर पर, प्रतिमा का एक आधा हिस्सा शिव की विशेषताओं, जैसे त्रिशूल और जटाओं को प्रदर्शित करता है, जबकि दूसरा आधा हिस्सा विष्णु के प्रतीक जैसे शंख और चक्र को दिखाता है। इस तरह की कलाकृतियां सांस्कृतिक रूप से महत्वपूर्ण हैं क्योंकि वे हिंदू धर्म की समन्वयवादी प्रकृति और वैष्णव और शैव परंपराओं में सामंजस्य स्थापित करने के ऐतिहासिक प्रयासों को दर्शाती हैं, जो विभिन्न संप्रदायों के बीच सहिष्णुता और एकता को बढ़ावा देती हैं।',
      kn: 'ಈ ಗಮನಾರ್ಹ ಪ್ರತಿಮೆಯು ಸಂಯೋಜಿತ ಹಿಂದೂ ದೇವತೆಯಾದ ಹರಿಹರನನ್ನು ಸಾಕಾರಗೊಳಿಸುತ್ತದೆ, ಇದು ವಿಷ್ಣು (ಹರಿ) ಮತ್ತು ಶಿವ (ಹರ) ರ ಸಮ್ಮಿಳನವನ್ನು ಪ್ರತಿನಿಧಿಸುವ ಏಕತೆಯ ಪ್ರಬಲ ಸಂಕೇತವಾಗಿದೆ. ಈ ರೂಪವು ಈ ಇಬ್ಬರು ಪ್ರಮುಖ ದೇವರುಗಳು ಒಂದೇ ಅಂತಿಮ ವಾಸ್ತವದ, ಬ್ರಹ್ಮನ ವಿಭಿನ್ನ ಅಂಶಗಳಾಗಿವೆ ಎಂಬ ತಾತ್ವಿಕ ಪರಿಕಲ್ಪನೆಯನ್ನು ವಿವರಿಸುತ್ತದೆ. ವಿಶಿಷ್ಟವಾಗಿ, ಪ್ರತಿಮೆಯ ಒಂದು ಅರ್ಧವು ಶಿವನ ಗುಣಲಕ್ಷಣಗಳನ್ನು ಪ್ರದರ್ಶಿಸುತ್ತದೆ, ಉದಾಹರಣೆಗೆ ತ್ರಿಶೂಲ ಮತ್ತು ಜಡೆ ಕೂದಲು, ಇನ್ನೊಂದು ಅರ್ಧವು ವಿಷ್ಣುವಿನ ಚಿಹ್ನೆಗಳಾದ ಶಂಖ ಮತ್ತು ಚಕ್ರವನ್ನು ತೋರಿಸುತ್ತದೆ. ಅಂತಹ ಕಲಾಕೃತಿಗಳು ಸಾಂಸ್ಕೃತಿಕವಾಗಿ ಮಹತ್ವದ್ದಾಗಿವೆ ಏಕೆಂದರೆ ಅವು ಹಿಂದೂ ಧರ್ಮದ ಸಿಂಕ್ರೆಟಿಕ್ ಸ್ವಭಾವವನ್ನು ಮತ್ತು ವೈಷ್ಣವ ಮತ್ತು ಶೈವ ಸಂಪ್ರದಾಯಗಳನ್ನು ಸಮನ್ವಯಗೊಳಿಸುವ ಐತಿಹಾಸಿಕ ಪ್ರಯತ್ನಗಳನ್ನು ಪ್ರತಿಬಿಂಬಿಸುತ್ತವೆ, ವಿವಿಧ ಪಂಗಡಗಳ ನಡುವೆ ಸಹಿಷ್ಣುತೆ ಮತ್ತು ಏಕತೆಯನ್ನು ಉತ್ತೇಜಿಸುತ್ತವೆ.',
      or: 'ଏହି ଉଲ୍ଲେଖନୀୟ ପ୍ରତିମୂର୍ତ୍ତି ମିଶ୍ରିତ ହିନ୍ଦୁ ଦେବତା ହରିହରଙ୍କୁ ମୂର୍ତ୍ତିମନ୍ତ କରେ, ଯାହା ବିଷ୍ଣୁ (ହରି) ଏବଂ ଶିବ (ହର)ଙ୍କ ମିଶ୍ରଣକୁ ପ୍ରତିନିଧିତ୍ୱ କରୁଥିବା ଏକତାର ଏକ ଶକ୍ତିଶାଳୀ ପ୍ରତୀକ। ଏହି ରୂପ ଦାର୍ଶନିକ ଧାରଣାକୁ ବର୍ଣ୍ଣନା କରେ ଯେ ଏହି ଦୁଇ ପ୍ରମୁଖ ଦେବତା ଗୋଟିଏ ପରମ ସତ୍ୟ, ବ୍ରହ୍ମଙ୍କର ଭିନ୍ନ ଭିନ୍ନ ଦିଗ। ସାଧାରଣତଃ, ପ୍ରତିମୂର୍ତ୍ତିର ଗୋଟିଏ ଅଧା ଶିବଙ୍କ ଗୁଣ, ଯେପରିକି ତ୍ରିଶୂଳ ଏବଂ ଜଟା, ପ୍ରଦର୍ଶନ କରେ, ଯେତେବେଳେ କି ଅନ୍ୟ ଅଧା ବିଷ୍ଣୁଙ୍କ ପ୍ରତୀକ ଯେପରିକି ଶଙ୍ଖ ଏବଂ ଚକ୍ର ଦେଖାଏ। ଏହିପରି କଳାକୃତି ସାଂସ୍କୃତିକ ଦୃଷ୍ଟିରୁ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ କାରଣ ସେମାନେ ହିନ୍ଦୁ ଧର୍ମର ସମନ୍ୱୟବାଦୀ ପ୍ରକୃତି ଏବଂ ବୈଷ୍ଣବ ଏବଂ ଶୈବ ପରମ୍ପରାକୁ ସମନ୍ୱୟ କରିବାର ଐତିହାସିକ ପ୍ରୟାସକୁ ପ୍ରତିଫଳିତ କରନ୍ତି, ଯାହା ବିଭିନ୍ନ ସମ୍ପ୍ରଦାୟ ମଧ୍ୟରେ ସହିଷ୍ଣୁତା ଏବଂ ଏକତାକୁ ପ୍ରୋତ୍ସାହିତ କରେ।',
    },
    imageUrlId: 'harihara-artifact',
    modelFileUrl: '/models/harihara_statue.glb',
    lowPolyModelUrl: '/models/harihara_statue_low.glb',
    fallbackImageUrlId: 'harihara-artifact',
  },
  {
    id: 'art-6',
    siteId: 'site-8',
    title: {
      en: 'Chhau Mask',
      hi: 'छऊ मुखौटा',
      kn: 'ಛೌ ಮುಖೋಟ್ಟು',
      or: 'ଛଉ ମୁଖା',
    },
    description: {
      en: 'The Chhau mask is an integral part of the Chhau dance, a vibrant and dynamic semi-classical Indian dance form with origins in the martial, tribal, and folk traditions of Eastern India. Specifically associated with Purulia in West Bengal, Seraikela in Jharkhand, and Mayurbhanj in Odisha, these masks are masterpieces of artistry. They are traditionally made by artisans from the Sutradhar community using a meticulous process of layering paper, cloth, and clay over a mold. The masks depict a wide range of characters, from gods and goddesses like Durga and Ganesha to demons and animals, each with distinct colors and expressions that are central to the storytelling of the dance.',
      hi: 'छऊ मुखौटा छऊ नृत्य का एक अभिन्न अंग है, जो पूर्वी भारत की मार्शल, आदिवासी और लोक परंपराओं से उत्पन्न एक जीवंत और गतिशील अर्ध-शास्त्रीय भारतीय नृत्य शैली है। विशेष रूप से पश्चिम बंगाल में पुरुलिया, झारखंड में सरायकेला और ओडिशा में मयूरभंज से जुड़े ये मुखौटे कलात्मकता के उत्कृष्ट नमूने हैं। इन्हें पारंपरिक रूप से सूत्रधार समुदाय के कारीगरों द्वारा एक सांचे पर कागज, कपड़े और मिट्टी की परतें चढ़ाकर एक सावधानीपूर्वक प्रक्रिया का उपयोग करके बनाया जाता है। मुखौटे दुर्गा और गणेश जैसे देवी-देवताओं से लेकर राक्षसों और जानवरों तक के पात्रों की एक विस्तृत श्रृंखला को दर्शाते हैं, जिनमें से प्रत्येक में अलग-अलग रंग और भाव होते हैं जो नृत्य की कहानी कहने के केंद्र में होते हैं।',
      kn: 'ಛೌ ಮುಖವಾಡವು ಛೌ ನೃತ್ಯದ ಅವಿಭಾಜ್ಯ ಅಂಗವಾಗಿದೆ, ಇದು ಪೂರ್ವ ಭಾರತದ ಸಮರ, ಬುಡಕಟ್ಟು ಮತ್ತು ಜಾನಪದ ಸಂಪ್ರದಾಯಗಳಲ್ಲಿ ಮೂಲವನ್ನು ಹೊಂದಿರುವ ರೋಮಾಂಚಕ ಮತ್ತು ಕ್ರಿಯಾತ್ಮಕ ಅರೆ-ಶಾಸ್ತ್ರೀಯ ಭಾರತೀಯ ನೃತ್ಯ ಪ್ರಕಾರವಾಗಿದೆ. ಪಶ್ಚಿಮ ಬಂಗಾಳದ ಪುರುಲಿಯಾ, ಜಾರ್ಖಂಡ್‌ನ ಸೆರೈಕೆಲಾ ಮತ್ತು ಒಡಿಶಾದ ಮಯೂರ್‌ಭಂಜ್‌ಗೆ ನಿರ್ದಿಷ್ಟವಾಗಿ ಸಂಬಂಧಿಸಿದೆ, ಈ ಮುಖವಾಡಗಳು ಕಲಾತ್ಮಕತೆಯ ಮೇರುಕೃತಿಗಳಾಗಿವೆ. ಅವುಗಳನ್ನು ಸಾಂಪ್ರದಾಯಿಕವಾಗಿ ಸೂತ್ರಧಾರ್ ಸಮುದಾಯದ ಕುಶಲಕರ್ಮಿಗಳು ಅಚ್ಚಿನ ಮೇಲೆ ಕಾಗದ, ಬಟ್ಟೆ ಮತ್ತು ಜೇಡಿಮಣ್ಣಿನ ಪದರವನ್ನು ಹಾಕುವ ನಿಖರವಾದ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಬಳಸಿ ತಯಾರಿಸುತ್ತಾರೆ. ಮುಖವಾಡಗಳು ದುರ್ಗಾ ಮತ್ತು ಗಣೇಶನಂತಹ ದೇವರು ಮತ್ತು ದೇವತೆಗಳಿಂದ ಹಿಡಿದು ರಾಕ್ಷಸರು ಮತ್ತು ಪ್ರಾಣಿಗಳವರೆಗಿನ ವ್ಯಾಪಕ ಶ್ರೇಣಿಯ ಪಾತ್ರಗಳನ್ನು ಚಿತ್ರಿಸುತ್ತವೆ, ಪ್ರತಿಯೊಂದೂ ವಿಭಿನ್ನ ಬಣ್ಣಗಳು ಮತ್ತು ಅಭಿವ್ಯಕ್ತಿಗಳನ್ನು ಹೊಂದಿದ್ದು ಅದು ನೃತ್ಯದ ಕಥೆ ಹೇಳುವಿಕೆಗೆ ಕೇಂದ್ರವಾಗಿದೆ.',
      or: 'ଛଉ ମୁଖା ଛଉ ନୃତ୍ୟର ଏକ ଅବିଚ୍ଛେଦ୍ୟ ଅଙ୍ଗ, ଯାହା ପୂର୍ବ ଭାରତର ସାମରିକ, ଆଦିବାସୀ ଏବଂ ଲୋକ ପରମ୍ପରାରୁ ଉତ୍ପନ୍ନ ଏକ ଜୀବନ୍ତ ଏବଂ ଗତିଶୀଳ ଅର୍ଦ୍ଧ-ଶାସ୍ତ୍ରୀୟ ଭାରତୀୟ ନୃତ୍ୟ। ପଶ୍ଚିମବଙ୍ଗର ପୁରୁଲିଆ, ଝାଡ଼ଖଣ୍ଡର ଷଢ଼େଇକଳା ଏବଂ ଓଡ଼ିଶାର ମୟୂରଭଞ୍ଜ ସହିତ ବିଶେଷ ଭାବରେ ଜଡିତ, ଏହି ମୁଖାଗୁଡ଼ିକ କଳାକାରିତାର ଶ୍ରେଷ୍ଠ କୃତି। ସେମାନଙ୍କୁ ପାରମ୍ପରିକ ଭାବରେ ସୂତ୍ରଧର ସମ୍ପ୍ରଦାୟର କାରିଗରମାନଙ୍କ ଦ୍ୱାରା ଏକ ଛାଞ୍ଚ ଉପରେ କାଗଜ, କପଡା ଏବଂ ମାଟିର ସ୍ତର ବିछାଇବାର ଏକ ସୂକ୍ଷ୍ମ ପ୍ରକ୍ରିୟା ବ୍ୟବହାର କରି ତିଆରି କରାଯାଏ। ମୁଖାଗୁଡ଼ିକ ଦୁର୍ଗା ଏବଂ ଗଣେଶଙ୍କ ପରି ଦେବଦେବୀଙ୍କଠାରୁ ଆରମ୍ଭ କରି ରାକ୍ଷସ ଏବଂ ପଶୁ ପର୍ଯ୍ୟନ୍ତ ବ୍ୟାପକ ଚରିତ୍ରକୁ ଚିତ୍ରଣ କରେ, ପ୍ରତ୍ୟେକଙ୍କର ଭିନ୍ନ ଭିନ୍ନ ରଙ୍ଗ ଏବଂ ଅଭିବ୍ୟକ୍ତି ରହିଛି ଯାହା ନୃତ୍ୟର କାହାଣୀ କହିବାରେ କେନ୍ଦ୍ରୀୟ ଅଟେ।',
    },
    imageUrlId: 'chhau-mask-artifact',
    modelFileUrl: '/models/chhau_mask.glb',
    lowPolyModelUrl: '/models/chhau_mask_low.glb',
    fallbackImageUrlId: 'chhau-mask-artifact',
  },
  {
    id: 'art-7',
    siteId: 'site-4',
    title: {
      en: 'Konark Wheel',
      hi: 'कोणार्क चक्र',
      kn: 'ಕೋನಾರ್ಕ್ ಚಕ್ರ',
      or: 'କୋଣାର୍କ ଚକ',
    },
    description: {
      en: 'This intricately carved stone wheel is one of twenty-four such wheels adorning the base of the Konark Sun Temple, a monumental structure designed as the chariot of the sun god, Surya. Each wheel, approximately 3 meters in diameter, is a masterpiece of 13th-century Kalingan architecture. More than just a decorative element, these wheels serve as functional sundials. The spokes of the wheels create a sundial where the time of day can be calculated with remarkable accuracy by observing the shadow cast by the central axle. The carvings on the wheels depict various aspects of life, including mythological figures, dancers, and scenes of daily activity, making them a rich tapestry of medieval life.',
      hi: 'यह जटिल रूप से नक्काशीदार पत्थर का पहिया कोणार्क सूर्य मंदिर के आधार को सुशोभित करने वाले चौबीस ऐसे पहियों में से एक है, जो सूर्य देव, सूर्य के रथ के रूप में डिजाइन की गई एक स्मारकीय संरचना है। प्रत्येक पहिया, लगभग 3 मीटर व्यास का, 13वीं शताब्दी की कलिंग वास्तुकला का एक उत्कृष्ट नमूना है। केवल एक सजावटी तत्व से अधिक, ये पहिये कार्यात्मक सूर्य घड़ियों के रूप में काम करते हैं। पहियों की तीलियाँ एक सूर्य घड़ी बनाती हैं जहाँ केंद्रीय धुरी द्वारा डाली गई छाया को देखकर दिन के समय की गणना उल्लेखनीय सटीकता के साथ की जा सकती है। पहियों पर की गई नक्काशी पौराणिक आकृतियों, नर्तकियों और दैनिक गतिविधियों के दृश्यों सहित जीवन के विभिन्न पहलुओं को दर्शाती है, जो उन्हें मध्ययुगीन जीवन का एक समृद्ध चित्र बनाती है।',
      kn: 'ಈ ಸಂಕೀರ್ಣವಾಗಿ ಕೆತ್ತಿದ ಕಲ್ಲಿನ ಚಕ್ರವು ಕೋನಾರ್ಕ್ ಸೂರ್ಯ ದೇವಾಲಯದ ತಳವನ್ನು ಅಲಂಕರಿಸುವ ಇಪ್ಪತ್ತನಾಲ್ಕು ಚಕ್ರಗಳಲ್ಲಿ ಒಂದಾಗಿದೆ, ಇದು ಸೂರ್ಯ ದೇವರಾದ ಸೂರ್ಯನ ರಥವಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ಒಂದು ಸ್ಮಾರಕ ರಚನೆಯಾಗಿದೆ. ಸರಿಸುಮಾರು 3 ಮೀಟರ್ ವ್ಯಾಸದ ಪ್ರತಿಯೊಂದು ಚಕ್ರವು 13 ನೇ ಶತಮಾನದ ಕಳಿಂಗ ವಾಸ್ತುಶಿಲ್ಪದ ಮೇರುಕೃತಿಯಾಗಿದೆ. ಕೇವಲ ಅಲಂಕಾರಿಕ ಅಂಶಕ್ಕಿಂತ ಹೆಚ್ಚಾಗಿ, ಈ ಚಕ್ರಗಳು ಕ್ರಿಯಾತ್ಮಕ ಸೂರ್ಯನ ಗಡಿಯಾರಗಳಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ. ಚಕ್ರಗಳ ಕಂಬಿಗಳು ಸೂರ್ಯನ ಗಡಿಯಾರವನ್ನು ರಚಿಸುತ್ತವೆ, ಅಲ್ಲಿ ಕೇಂದ್ರ ಆಕ್ಸల్‌ನಿಂದ ಎರಕಹೊಯ್ದ ನೆರಳನ್ನು ಗಮನಿಸುವುದರ ಮೂಲಕ ದಿನದ ಸಮಯವನ್ನು ಗಮನಾರ್ಹ ನಿಖರತೆಯೊಂದಿಗೆ ಲೆಕ್ಕಹಾಕಬಹುದು. ಚಕ್ರಗಳ ಮೇಲಿನ ಕೆತ್ತನೆಗಳು ಪೌರಾಣಿಕ ವ್ಯಕ್ತಿಗಳು, ನರ್ತಕರು ಮತ್ತು ದೈನಂದಿನ ಚಟುವಟಿಕೆಯ ದೃಶ್ಯಗಳು ಸೇರಿದಂತೆ ಜೀವನದ ವಿವಿಧ ಅಂಶಗಳನ್ನು ಚಿತ್ರಿಸುತ್ತವೆ, ಅವುಗಳನ್ನು ಮಧ್ಯಕಾಲೀನ ಜೀವನದ ಶ್ರೀಮಂತ ವಸ್ತ್ರವನ್ನಾಗಿ ಮಾಡುತ್ತದೆ.',
      or: 'ଏହି ଜଟିଳ ଭାବରେ ଖୋଦିତ ପଥର ଚକ କୋଣାର୍କ ସୂର୍ଯ୍ୟ ମନ୍ଦିରର ମୂଳଦୁଆକୁ ସଜାଇଥିବା ଚବିଶଟି ଚକ ମଧ୍ୟରୁ ଗୋଟିଏ, ଯାହା ସୂର୍ଯ୍ୟ ଦେବତା ସୂର୍ଯ୍ୟଙ୍କ ରଥ ଭାବରେ ପରିକଳ୍ପିତ ଏକ ସ୍ମାରକୀ ସଂରଚନା। ପ୍ରାୟ ୩ ମିଟର ବ୍ୟାସ ବିଶିଷ୍ଟ ପ୍ରତ୍ୟେକ ଚକ, ୧୩ଶ ଶତାବ୍ଦୀର କଳିଙ୍ଗ ସ୍ଥାପତ୍ୟର ଏକ ଶ୍ରେଷ୍ଠ କୃତି। କେବଳ ଏକ ସାଜସଜ୍ଜା ଉପାଦାନଠାରୁ ଅଧିକ, ଏହି ଚକଗୁଡ଼ିକ କାର୍ଯ୍ୟକ୍ଷମ ସୂର୍ଯ୍ୟଘଡ଼ି ଭାବରେ କାର୍ଯ୍ୟ କରନ୍ତି। ଚକଗୁଡ଼ିକର ସ୍ପୋକ୍ସ ଏକ ସୂର୍ଯ୍ୟଘଡ଼ି ସୃଷ୍ଟି କରେ ଯେଉଁଠାରେ କେନ୍ଦ୍ରୀୟ ଆକ୍ସଲ୍ ଦ୍ୱାରା ପକାଯାଇଥିବା ଛାୟାକୁ ଦେଖି ଦିନର ସମୟକୁ ଉଲ୍ଲେଖନୀୟ ସଠିକତା ସହିତ ଗଣନା କରାଯାଇପାରିବ। ଚକଗୁଡ଼ିକ ଉପରେ ଥିବା ଖୋଦେଇ ପୌରାଣିକ ଚରିତ୍ର, ନୃତ୍ୟଶିଳ୍ପୀ ଏବଂ ଦୈନନ୍ଦିନ କାର୍ଯ୍ୟକଳାପର ଦୃଶ୍ୟ ସମେତ ଜୀବନର ବିଭିନ୍ନ ଦିଗକୁ ଚିତ୍ରଣ କରେ, ଯାହା ସେମାନଙ୍କୁ ମଧ୍ୟଯୁଗୀୟ ଜୀବନର ଏକ ସମୃଦ୍ଧ ଚିତ୍ରପଟ୍ଟ କରିଥାଏ।',
    },
    imageUrlId: 'konark-wheel-artifact',
    modelFileUrl: '/models/konark_wheel.glb',
    lowPolyModelUrl: '/models/konark_wheel_low.glb',
    fallbackImageUrlId: 'konark-wheel-artifact',
  },
];

const allSites: Site[] = [
  {
    id: 'site-1',
    title: {
      en: 'Taj Mahal',
      hi: 'ताज महल',
      kn: 'ತಾಜ್ ಮಹಲ್',
      or: 'ତାଜମହଲ',
    },
    shortDescription: {
      en: 'An ivory-white marble mausoleum on the south bank of the Yamuna river.',
      hi: 'यमुना नदी के दक्षिणी तट पर एक हाथीदांत-सफेद संगमरमर का मकबरा।',
      kn: 'ಯಮುನಾ ನದಿಯ ದಕ್ಷಿಣ ತೀರದಲ್ಲಿ ಇರಿಸಿಕೊಡಲಿರುವ ಬಿಳಿ ಸಂಗ್ರಹ ಶಿಲಾ ಸಮಾಧಿ।',
      or: 'ଯମୁନା ନଦୀର ଦକ୍ଷିଣ କୂଳରେ ଥିବା ଏକ ହାତୀଦାନ୍ତ-ଧଳା ମାର୍ବଲ ସମାଧି।',
    },
    longDescription: {
      en: 'The Taj Mahal, located in Agra, India, is an immense mausoleum of shimmering white marble, built between 1631 and 1648. It was commissioned by the Mughal emperor Shah Jahan as a testament of eternal love for his favorite wife, Mumtaz Mahal, who died during childbirth. This architectural marvel is widely regarded as "the jewel of Muslim art in India" and one of the universally admired masterpieces of the world\'s heritage. The complex stands on a vast 42-acre site and includes a main gateway, a mosque, a guest house, and beautifully landscaped gardens, all set in perfect symmetry. The central dome is surrounded by four smaller domes and four slender minarets, creating a breathtaking skyline that reflects in the tranquil waters of the Yamuna river. The intricate details, including pietra dura inlays of semi-precious stones and calligraphic verses from the Quran, make it a monument of unparalleled beauty and grandeur.',
      hi: 'भारत के आगरा में स्थित ताजमहल, चमचमाते सफेद संगमरमर का एक विशाल मकबरा है, जिसका निर्माण 1631 और 1648 के बीच हुआ था। इसे मुगल सम्राट शाहजहाँ ने अपनी पसंदीदा पत्नी मुमताज महल के प्रति शाश्वत प्रेम के प्रमाण के रूप में बनवाया था, जिनकी प्रसव के दौरान मृत्यु हो गई थी। इस स्थापत्य चमत्कार को व्यापक रूप से "भारत में मुस्लिम कला का गहना" और दुनिया की विरासत की सार्वभौमिक रूप से प्रशंसित उत्कृष्ट कृतियों में से एक माना जाता है। यह परिसर 42 एकड़ की विशाल साइट पर खड़ा है और इसमें एक मुख्य प्रवेश द्वार, एक मस्जिद, एक गेस्ट हाउस और खूबसूरती से सजाए गए बगीचे शामिल हैं, जो सभी पूर्ण समरूपता में स्थापित हैं। केंद्रीय गुंबद चार छोटे गुंबदों और चार पतली मीनारों से घिरा हुआ है, जो एक लुभावनी क्षितिज बनाता है जो यमुना नदी के शांत पानी में प्रतिबिंबित होता है। अर्द्ध-कीमती पत्थरों की पिएट्रा ड्यूरा जड़ाई और कुरान से सुलेख छंद सहित जटिल विवरण, इसे अद्वितीय सुंदरता और भव्यता का स्मारक बनाते हैं।',
      kn: 'ಭಾರತದ ಆಗ್ರಾದಲ್ಲಿರುವ ತಾಜ್ ಮಹಲ್, 1631 ಮತ್ತು 1648 ರ ನಡುವೆ ನಿರ್ಮಿಸಲಾದ ಹೊಳೆಯುವ ಬಿಳಿ ಅಮೃತಶಿಲೆಯ ಬೃಹತ್ ಸಮಾಧಿಯಾಗಿದೆ. ಇದನ್ನು ಮೊಘಲ್ ಚಕ್ರವರ್ತಿ ಷಹಜಹಾನ್ ತನ್ನ ನೆಚ್ಚಿನ ಹೆಂಡತಿ ಮುಮ್ತಾಜ್ ಮಹಲ್ ಮೇಲಿನ ಶಾಶ್ವತ ಪ್ರೀತಿಯ ದ್ಯೋತಕವಾಗಿ ನಿಯೋಜಿಸಿದನು, ಅವಳು ಹೆರಿಗೆಯ ಸಮಯದಲ್ಲಿ ನಿಧನಳಾದಳು. ಈ ವಾಸ್ತುಶಿಲ್ಪದ ಅದ್ಭುತವನ್ನು "ಭಾರತದಲ್ಲಿ ಮುಸ್ಲಿಂ ಕಲೆಯ ಆಭರಣ" ಮತ್ತು ವಿಶ್ವದ ಪರಂಪರೆಯ ಸಾರ್ವತ್ರಿಕವಾಗಿ ಮೆಚ್ಚುಗೆ ಪಡೆದ ಮೇರುಕೃತಿಗಳಲ್ಲಿ ಒಂದೆಂದು ವ್ಯಾಪಕವಾಗಿ ಪರಿಗಣಿಸಲಾಗಿದೆ. ಈ ಸಂಕೀರ್ಣವು 42-ಎಕರೆ ವಿಶಾಲವಾದ ಸ್ಥಳದಲ್ಲಿ ನಿಂತಿದೆ ಮತ್ತು ಮುಖ್ಯ ಗೇಟ್‌ವೇ, ಮಸೀದಿ, ಅತಿಥಿ ಗೃಹ ಮತ್ತು ಸುಂದರವಾಗಿ ಭೂದೃಶ್ಯದ ಉದ್ಯಾನಗಳನ್ನು ಒಳಗೊಂಡಿದೆ, ಎಲ್ಲವನ್ನೂ ಪರಿಪೂರ್ಣ ಸಮ್ಮಿತಿಯಲ್ಲಿ ಹೊಂದಿಸಲಾಗಿದೆ. ಕೇಂದ್ರ ಗುಮ್ಮಟವು ನಾಲ್ಕು ಸಣ್ಣ ಗುಮ್ಮಟಗಳು ಮತ್ತು ನಾಲ್ಕು ತೆಳುವಾದ ಮಿನಾರ್‌ಗಳಿಂದ ಆವೃತವಾಗಿದೆ, ಇದು ಯಮುನಾ ನದಿಯ ಪ್ರಶಾಂತ ನೀರಿನಲ್ಲಿ ಪ್ರತಿಫಲಿಸುವ ಉಸಿರುಕಟ್ಟುವ ಸ್ಕೈಲೈನ್ ಅನ್ನು ರಚಿಸುತ್ತದೆ. ಅರೆ-ಅಮೂಲ್ಯ ಕಲ್ಲುಗಳ ಪಿಯೆಟ್ರಾ ಡುರಾ ಇನ್ಲೇಗಳು ಮತ್ತು ಕುರಾನ್‌ನಿಂದ ಕ್ಯಾಲಿಗ್ರಾಫಿಕ್ ಪದ್ಯಗಳು ಸೇರಿದಂತೆ ಸಂಕೀರ್-ಣದ ವಿವರಗಳು, ಇದನ್ನು ಸಾಟಿಯಿಲ್ಲದ ಸೌಂದರ್ಯ ಮತ್ತು ಭವ್ಯತೆಯ ಸ್ಮಾರಕವನ್ನಾಗಿ ಮಾಡುತ್ತದೆ.',
      or: 'ଭାରତର ଆଗ୍ରାରେ ଅବସ୍ଥିତ ତାଜମହଲ, ୧୬୩୧ ରୁ ୧୬୪୮ ମଧ୍ୟରେ ନିର୍ମିତ ଏକ ବିଶାଳ ଧଳା ମାର୍ବଲର ସମାଧି। ଏହାକୁ ମୋଗଲ ସମ୍ରାଟ ଶାହଜାହାନ ତାଙ୍କର ପ୍ରିୟ ପତ୍ନୀ ମମତାଜ ମହଲଙ୍କ ପ୍ରତି ଅନନ୍ତ ପ୍ରେମର ପ୍ରମାଣ ସ୍ୱରୂପ ନିର୍ମାଣ କରିଥିଲେ, ଯିଏ ପ୍ରସବ ସମୟରେ ମୃତ୍ୟୁବରଣ କରିଥିଲେ। ଏହି ସ୍ଥାପତ୍ୟର ଚମତ୍କାରକୁ "ଭାରତରେ ମୁସଲିମ କଳାର ରତ୍ନ" ଏବଂ ବିଶ୍ୱ ଐତିହ୍ୟର ସର୍ବଭାରତୀୟ ପ୍ରଶଂସିତ କୃତି ମଧ୍ୟରୁ ଗୋଟିଏ ଭାବରେ ବ୍ୟାପକ ଭାବରେ ବିବେଚନା କରାଯାଏ। ଏହି କମ୍ପ୍ଲେକ୍ସ ୪୨ ଏକର ବିଶାଳ ସ୍ଥାନରେ ଛିଡା ହୋଇଛି ଏବଂ ଏଥିରେ ଏକ ମୁଖ୍ୟ ପ୍ରବେଶ ଦ୍ୱାର, ଏକ ମସଜିଦ, ଏକ ଅତିଥି ଗୃହ, ଏବଂ ସୁନ୍ଦର ଭାବରେ ସଜ୍ଜିତ ବଗିଚା ଅନ୍ତର୍ଭୁକ୍ତ, ଯାହା ସବୁ ସମ୍ପୂର୍ଣ୍ଣ ସମମିତିରେ ସ୍ଥାପିତ ହୋଇଛି। କେନ୍ଦ୍ରୀୟ ଗମ୍ବୁଜ ଚାରୋଟି ଛୋଟ ଗମ୍ବୁଜ ଏବଂ ଚାରୋଟି ପତଳା ମିନାର ଦ୍ୱାରା ଘେରି ରହିଛି, ଯାହା ଯମୁନା ନଦୀର ଶାନ୍ତ ଜଳରେ ପ୍ରତିଫଳିତ ହେଉଥିବା ଏକ ଚମତ୍କାର ଆକାଶ ରେଖା ସୃଷ୍ଟି କରେ। ଅର୍ଦ୍ଧ-ମୂଲ୍ୟବାନ ପଥରର ପିଟ୍ରା ଡୁରା ଜଡ଼ିତ କାର୍ଯ୍ୟ ଏବଂ କୁରାନରୁ କାଲିଗ୍ରାଫିକ୍ ପଦ ସହିତ ଜଟିଳ ବିବରଣୀ, ଏହାକୁ ଅତୁଳନୀୟ ସୌନ୍ଦର୍ଯ୍ୟ ଏବଂ ଭବ୍ୟତାର ଏକ ସ୍ମାରକ କରିଥାଏ।',
    },
    thumbnailUrlId: 'taj-mahal-thumb',
    coverImageUrlId: 'taj-mahal-cover',
    lowPolyModelUrl: '/models/taj_low.glb',
    highPolyModelUrl: '/models/taj_mahal_3d_model.glb',
    fallback360UrlId: 'fallback-360-taj',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-1'),
    arLink: 'https://arvr.google.com/scene-viewer/1.0?file=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF/DamagedHelmet.gltf',
  },
  {
    id: 'site-2',
    title: {
      en: 'Hampi Chariot',
      kn: 'ಹಂಪಿ ರಥ',
      hi: 'हम्पी रथ',
      or: 'ହାମ୍ପି ରଥ',
    },
    shortDescription: {
      en: 'The ruined city of Vijayanagara, the former capital of the Vijayanagara Empire.',
      hi: 'विजयनगर का खंडहर शहर, विजयनगर साम्राज्य की पूर्व राजधानी।',
      kn: 'ವಿಜಯನಗರದ ಹರಡಿರುವ ಹಾಳಾದ ನಗರ, ಈ ಪ್ರದೇಶ ಐತಿಹಾಸಿಕವಾಗಿ ವಿಜಯನಗರ ಸಾಮ್ರಾಜ್ಯದ ರಾಜಧಾನಿಯಾಗಿತ್ತು।',
      or: 'ବିଜୟନଗରର ଧ୍ୱଂସାବଶେଷ ସହର, ବିଜୟନଗର ସାମ୍ରାଜ୍ୟର ପୂର୍ବତନ ରାଜଧାନୀ।',
    },
    longDescription: {
      en: 'Hampi, a UNESCO World Heritage Site, is the former capital of the formidable Vijayanagara Empire. Spread across a vast, rocky landscape in Karnataka, the ruins tell the story of a once-thriving metropolis. At the heart of its most sacred enclosure stands the iconic Stone Chariot in the Vittala Temple Complex. This is not a chariot in the traditional sense but a monolithic shrine dedicated to Garuda, the mount of Lord Vishnu. The structure is renowned for its exceptional artistry, with giant stone wheels that could once be rotated. This architectural marvel, along with over 1,600 other surviving remains including forts, temples, and royal complexes, makes Hampi a captivating open-air museum, showcasing the pinnacle of Dravidian art and architecture during the 14th to 16th centuries.',
      hi: 'हम्पी, एक यूनेस्को विश्व धरोहर स्थल, दुर्जेय विजयनगर साम्राज्य की पूर्व राजधानी है। कर्नाटक में एक विशाल, चट्टानी परिदृश्य में फैले, ये खंडहर एक समय के संपन्न महानगर की कहानी बताते हैं। इसके सबसे पवित्र परिसर के केंद्र में विट्ठल मंदिर परिसर में प्रतिष्ठित पत्थर का रथ खड़ा है। यह पारंपरिक अर्थों में रथ नहीं है, बल्कि भगवान विष्णु के वाहन गरुड़ को समर्पित एक अखंड मंदिर है। यह संरचना अपनी असाधारण कलात्मकता के लिए प्रसिद्ध है, जिसमें विशाल पत्थर के पहिये हैं जिन्हें कभी घुमाया जा सकता था। यह वास्तुशिल्प चमत्कार, किलों, मंदिरों और शाही परिसरों सहित 1,600 से अधिक अन्य जीवित अवशेषों के साथ, हम्पी को एक मनोरम ओपन-एयर संग्रहालय बनाता है, जो 14वीं से 16वीं शताब्दी के दौरान द्रविड़ कला और वास्तुकला के शिखर को प्रदर्शित करता है।',
      kn: 'ಯುನೆಸ್ಕೋ ವಿಶ್ವ ಪರಂಪರೆಯ ತಾಣವಾದ ಹಂಪಿ, ಅಸಾಧಾರಣ ವಿಜಯನಗರ ಸಾಮ್ರಾಜ್ಯದ ಹಿಂದಿನ ರಾಜಧಾನಿಯಾಗಿದೆ. ಕರ್ನಾಟಕದ ವಿಶಾಲವಾದ, ಕಲ್ಲಿನ ಭೂದೃಶ್ಯದಲ್ಲಿ ಹರಡಿರುವ ಈ ಅವಶೇಷಗಳು ಒಮ್ಮೆ ಅಭಿವೃದ್ಧಿ ಹೊಂದುತ್ತಿರುವ ಮಹಾನಗರದ ಕಥೆಯನ್ನು ಹೇಳುತ್ತವೆ. ಅದರ ಅತ್ಯಂತ ಪವಿತ್ರವಾದ ಆವರಣದ ಹೃದಯಭಾಗದಲ್ಲಿ ವಿಠಲ ದೇವಾಲಯದ ಸಂಕೀರ್ಣದಲ್ಲಿ ಸಾಂప్రದಾಯಿಕ ಕಲ್ಲಿನ ರಥವಿದೆ. ಇದು ಸಾಂప్రದಾಯಿಕ ಅರ್ಥದಲ್ಲಿ ರಥವಲ್ಲ, ಆದರೆ ವಿಷ್ಣುವಿನ ವಾಹನವಾದ ಗರುಡನಿಗೆ ಸಮರ್ಪಿತವಾದ ಏಕಶಿಲೆಯ ದೇವಾಲಯವಾಗಿದೆ. ಈ ರಚನೆಯು ಅದರ ಅಸಾಧಾರಣ ಕಲಾತ್ಮಕತೆಗೆ ಹೆಸರುವಾಸಿಯಾಗಿದೆ, ಒಮ್ಮೆ ತಿರುಗಿಸಬಹುದಾದ ದೈತ್ಯ ಕಲ್ಲಿನ ಚಕ್ರಗಳನ್ನು ಹೊಂದಿದೆ. ಈ ವಾಸ್ತುಶಿಲ್ಪದ ಅದ್ಭುತ, ಕೋಟೆಗಳು, ದೇವಾಲಯಗಳು ಮತ್ತು ರಾಜಮನೆತನದ ಸಂಕೀರ್ಣಗಳನ್ನು ಒಳಗೊಂಡಂತೆ 1,600 ಕ್ಕೂ ಹೆಚ್ಚು ಉಳಿದಿರುವ ಅವಶೇಷಗಳೊಂದಿಗೆ, ಹಂಪಿಯನ್ನು ಆಕರ್ಷಕ ತೆರೆದ ಗಾಳಿ ವಸ್ತುಸಂಗ್ರಹಾಲಯವನ್ನಾಗಿ ಮಾಡುತ್ತದೆ, ಇದು 14 ರಿಂದ 16 ನೇ ಶತಮಾನಗಳಲ್ಲಿ ದ್ರಾವಿಡ ಕಲೆ ಮತ್ತು ವಾಸ್ತುಶಿಲ್ಪದ ಉತ್ತುಂಗವನ್ನು ಪ್ರದರ್ಶಿಸುತ್ತದೆ.',
      or: 'ହାମ୍ପି, ଏକ ୟୁନେସ୍କୋ ବିଶ୍ୱ ଐତିହ୍ୟ ସ୍ଥଳୀ, ଭୟଙ୍କର ବିଜୟନଗର ସାମ୍ରାଜ୍ୟର ପୂର୍ବତନ ରାଜଧାନୀ। କର୍ଣ୍ଣାଟକର ଏକ ବିଶାଳ, ପଥୁରିଆ ଭୂମିରେ ବ୍ୟାପିଥିବା ଏହି ଧ୍ୱଂସାବଶେଷ ଏକଦା ସମୃଦ୍ଧ ମହାନଗରର କାହାଣୀ କହେ। ଏହାର ସବୁଠାରୁ ପବିତ୍ର ପରିସରର କେନ୍ଦ୍ରରେ ବିଠ୍ଠଲ ମନ୍ଦିର ପରିସରରେ ପ୍ରତିଷ୍ଠିତ ପଥର ରଥ ଛିଡା ହୋଇଛି। ଏହା ପାରମ୍ପରିକ ଅର୍ଥରେ ଏକ ରଥ ନୁହେଁ, ବରଂ ଭଗବାନ ବିଷ୍ଣୁଙ୍କ ବାହନ ଗରୁଡ଼ଙ୍କୁ ସମର୍ପିତ ଏକ ଏକଶିଳା ମନ୍ଦିର। ଏହି ସଂରଚନା ଏହାର ଅସାଧାରଣ କଳାକାରିତା ପାଇଁ ପ୍ରସିଦ୍ଧ, ଯେଉଁଥିରେ ବିଶାଳ ପଥର ଚକ ଅଛି ଯାହାକୁ ଏକଦା ଘୂର୍ଣ୍ଣନ କରାଯାଇପାରୁଥିଲା। ଏହି ସ୍ଥାପତ୍ୟର ଚମତ୍କାର, ଦୁର୍ଗ, ମନ୍ଦିର ଏବଂ ରାଜକୀୟ ପରିସର ସମେତ ୧,୬୦୦ରୁ ଅଧିକ ଅବଶିଷ୍ଟ ଅବଶେଷ ସହିତ, ହାମ୍ପିକୁ ଏକ ମନୋରମ ଖୋଲା-ବାୟୁ ସଂଗ୍ରହାଳୟରେ ପରିଣତ କରେ, ଯାହା ୧୪ରୁ ୧୬ଶ ଶତାବ୍ଦୀ ମଧ୍ୟରେ ଦ୍ରାବିଡ଼ କଳା ଏବଂ ସ୍ଥାପତ୍ୟର ଶିଖର ପ୍ରଦର୍ଶନ କରେ।',
    },
    thumbnailUrlId: 'hampi-thumb',
    coverImageUrlId: 'hampi-cover',
    lowPolyModelUrl: '/models/hampi_low.glb',
    highPolyModelUrl: '/models/stone_chariot_in_hampi.glb',
    fallback360UrlId: 'fallback-360-hampi',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-2'),
    arLink: 'https://nizammhd.github.io/hampiar/',
  },
  {
    id: 'site-3',
    title: {
      en: 'Qutub Minar',
      hi: 'कुतुब मीनार',
      kn: 'ಕುತುಬ್ ಮಿನಾರ್',
      or: 'କୁତୁବ ମିନାର',
    },
    shortDescription: {
      en: 'A minaret and "victory tower" that forms part of the Qutb complex.',
      hi: 'कुतुब परिसर का एक मीनार और "विजय मंडप"।',
      kn: 'ಕುತುಬ್ ಸಂಕೀರ್ಣದಲ್ಲಿ ಭಾಗವಿರುವ ಮಿನಾರೆಟ್ ಮತ್ತು ವೀಕ್ಷಣ ಗೋಪುರ।',
      or: 'ଏକ ମିନାର ଏବଂ "ବିଜୟ ସ୍ତମ୍ଭ" ଯାହା କୁତବ କମ୍ପ୍ଲେକ୍ସର ଏକ ଅଂଶ।',
    },
    longDescription: {
      en: 'The Qutub Minar, a UNESCO World Heritage Site in Delhi, is a magnificent "victory tower" soaring to a height of 73 meters. Its construction was initiated in 1193 by Qutub-ud-Din Aibak, the first ruler of the Delhi Sultanate, to mark the beginning of Muslim rule in India. The tower was built over several generations, with subsequent additions by his successors Iltutmish and Firoz Shah Tughlaq. It features five distinct storeys, each marked by a projecting balcony and tapering as they ascend. The structure is a masterpiece of Indo-Islamic architecture, adorned with intricate carvings and verses from the Quran. The surrounding Qutb complex also includes other significant historical monuments, such as the Quwwat-ul-Islam Mosque and the famous Iron Pillar of Delhi, making it a rich archaeological area.',
      hi: 'दिल्ली में स्थित कुतुब मीनार, एक यूनेस्को विश्व धरोहर स्थल, 73 मीटर की ऊंचाई तक yükselen एक शानदार "विजय मीनार" है। इसका निर्माण 1193 में दिल्ली सल्तनत के पहले शासक कुतुब-उद-दीन ऐबक द्वारा भारत में मुस्लिम शासन की शुरुआत को चिह्नित करने के लिए शुरू किया गया था। इस मीनार का निर्माण कई पीढ़ियों तक चला, जिसमें उनके उत्तराधिकारियों इल्तुतमिश और फिरोज शाह तुगलक ने बाद में जोड़ा। इसमें पांच अलग-अलग मंजिलें हैं, जिनमें से प्रत्येक एक उभरी हुई बालकनी द्वारा चिह्नित है और ऊपर चढ़ते ही पतली होती जाती है। यह संरचना भारत-इस्लामी वास्तुकला का एक उत्कृष्ट नमूना है, जो जटिल नक्काशी और कुरान की आयतों से सुशोभित है। आसपास के कुतुब परिसर में कुव्वत-उल-इस्लाम मस्जिद और दिल्ली के प्रसिद्ध लौह स्तंभ जैसे अन्य महत्वपूर्ण ऐतिहासिक स्मारक भी शामिल हैं, जो इसे एक समृद्ध पुरातात्विक क्षेत्र बनाते हैं।',
      kn: 'ದೆಹಲಿಯ ಯುನೆಸ್ಕೋ ವಿಶ್ವ ಪರಂಪರೆಯ ತಾಣವಾದ ಕುತುಬ್ ಮಿನಾರ್ 73 ಮೀಟರ್ ಎತ್ತರಕ್ಕೆ ಏರುವ ಭವ್ಯವಾದ "ವಿಜಯ ಗೋಪುರ" ಆಗಿದೆ. ಇದರ ನಿರ್ಮಾಣವನ್ನು 1193 ರಲ್ಲಿ ದೆಹಲಿ ಸುಲ್ತಾನರ ಮೊದಲ ಆಡಳಿತಗಾರ ಕುತುಬ್-ಉದ್-ದಿನ್ ಐಬಕ್ ಭಾರತದಲ್ಲಿ ಮುಸ್ಲಿಂ ಆಳ್ವಿಕೆಯ ಆರಂಭವನ್ನು ಗುರುತಿಸಲು ಪ್ರಾರಂಭಿಸಿದರು. ಈ ಗೋಪುರವನ್ನು ಹಲವಾರು ತಲೆಮಾರುಗಳಿಂದ ನಿರ್ಮಿಸಲಾಯಿತು, ನಂತರ ಅವರ ಉತ್ತರಾಧಿಕಾರಿಗಳಾದ ಇಲ್ತುಮಿಶ್ ಮತ್ತು ಫಿರೋಜ್ ಷಾ ತುಘಲಕ್ ಅವರು ಸೇರಿಸಿದರು. ಇದು ಐದು ವಿಭಿನ್ನ ಮಹಡಿಗಳನ್ನು ಹೊಂದಿದೆ, ಪ್ರತಿಯೊಂದೂ ಚಾಚಿಕೊಂಡಿರುವ ಬಾಲ್ಕನಿಯಿಂದ ಗುರುತಿಸಲ್ಪಟ್ಟಿದೆ మరియు ಅವು ಏರುತ್ತಿದ್ದಂತೆ ಮೊನಚಾದವು. ಈ ರಚನೆಯು ಇಂಡೋ-ಇಸ್ಲಾಮಿಕ್ ವಾಸ್ತುಶಿಲ್ಪದ ಮೇರುಕೃತಿಯಾಗಿದೆ, ಇದು ಸಂಕೀರ್ಣವಾದ ಕೆತ್ತನೆಗಳು ಮತ್ತು ಕುರಾನ್‌ನ ಪದ್ಯಗಳಿಂದ ಅಲಂಕರಿಸಲ್ಪಟ್ಟಿದೆ. ಸುತ್ತಮುತ್ತಲಿನ ಕುತುಬ್ ಸಂಕೀರ್ಣವು ಕುವ್ವತ್-ಉಲ್-ಇಸ್ಲಾಂ ಮಸೀದಿ ಮತ್ತು ದೆಹಲಿಯ ಪ್ರಸಿದ್ಧ ಕಬ್ಬಿಣದ ಸ್ತಂಭದಂತಹ ಇತರ ಮಹತ್ವದ ಐತಿಹಾಸಿಕ ಸ್ಮಾರಕಗಳನ್ನು ಸಹ ಒಳಗೊಂಡಿದೆ, ಇದು ಶ್ರೀಮಂತ ಪುರಾತತ್ವ ಪ್ರದೇಶವಾಗಿದೆ.',
      or: 'ଦିଲ୍ଲୀର ଏକ ୟୁନେସ୍କୋ ବିଶ୍ୱ ଐତିହ୍ୟ ସ୍ଥଳୀ କୁତୁବ ମିନାର, ୭୩ ମିଟର ଉଚ୍ଚତା ବିଶିଷ୍ଟ ଏକ ଭବ୍ୟ "ବିଜୟ ସ୍ତମ୍ଭ"। ଏହାର ନିର୍ମାଣ ୧୧୯୩ ମସିହାରେ ଦିଲ୍ଲୀ ସୁଲତାନତର ପ୍ରଥମ ଶାସକ କୁତୁବ-ଉଦ-ଦିନ ଆଇବକଙ୍କ ଦ୍ୱାରା ଭାରତରେ ମୁସଲମାନ ଶାସନର ଆରମ୍ଭକୁ ଚିହ୍ନିତ କରିବା ପାଇଁ ଆରମ୍ଭ କରାଯାଇଥିଲା। ଏହି ଟାୱାରଟି ଅନେକ ପିଢ଼ି ଧରି ନିର୍ମିତ ହୋଇଥିଲା, ଏବଂ ପରବର୍ତ୍ତୀ ସମୟରେ ତାଙ୍କ ଉତ୍ତରାଧିକାରୀ ଇଲତୁତମିଶ ଏବଂ ଫିରୋଜ ଶାହ ତୋଗଲକଙ୍କ ଦ୍ୱାରା ଅତିରିକ୍ତ ନିର୍ମାଣ କରାଯାଇଥିଲା। ଏଥିରେ ପାଞ୍ଚଟି ଭିନ୍ନ ମହଲା ଅଛି, ପ୍ରତ୍ୟେକଟି ଏକ ବାହାରକୁ ବାହାରିଥିବା ବାଲକୋନି ଦ୍ୱାରା ଚିହ୍ନିତ ଏବଂ ଉପରକୁ ଯିବା ସମୟରେ ସଂକୀର୍ଣ୍ଣ ହୋଇଯାଏ। ଏହି ସଂରଚନା ଇଣ୍ଡୋ-ଇସଲାମିକ ସ୍ଥାପତ୍ୟର ଏକ ଶ୍ରେଷ୍ଠ କୃତି, ଯାହା ଜଟିଳ ଖୋଦେଇ ଏବଂ କୁରାନର ପଦ ଦ୍ୱାରା ସୁସଜ୍ଜିତ। ଏହାର ଆଖପାଖରେ ଥିବା କୁତୁବ କମ୍ପ୍ଲେକ୍ସରେ କୁୱତ-ଉଲ-ଇସଲାମ ମସଜିଦ ଏବଂ ଦିଲ୍ଲୀର ପ୍ରସିଦ୍ଧ ଲୌହ ସ୍ତମ୍ଭ ପରି ଅନ୍ୟାନ୍ୟ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ଐତିହାସିକ ସ୍ମାରକୀ ମଧ୍ୟ ଅନ୍ତର୍ଭୁକ୍ତ, ଯାହା ଏହାକୁ ଏକ ସମୃଦ୍ଧ ପ୍ରତ୍ନତାତ୍ତ୍ୱିକ ଅଞ୍ଚଳ କରିଥାଏ।',
    },
    thumbnailUrlId: 'qutub-minar-thumb',
    coverImageUrlId: 'qutub-minar-cover',
    lowPolyModelUrl: '/models/qutub_low.glb',
    highPolyModelUrl: '/models/qutub_minar.glb',
    fallback360UrlId: 'fallback-360-qutub',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-3'),
  },
  {
    id: 'site-4',
    title: {
      en: 'Konark Sun Temple',
      hi: 'कोणार्क सूर्य मंदिर',
      kn: 'ಕೋನಾರ್ಕ್ ಸೂರ್ಯ ದೇವಾಲಯ',
      or: 'କୋଣାର୍କ ସୂର୍ଯ୍ୟ ମନ୍ଦିର',
    },
    shortDescription: {
      en: 'A 13th-century CE sun temple at Konark in Odisha, India.',
      hi: 'ओडिशा के कोणार्क में 13वीं शताब्दी का सूर्य मंदिर।',
      kn: 'ಒಡಿಷಾದ ಕೊಣಾರ್ಕ್‌ನಲ್ಲಿ ಇರುವ 13ನೇ ಶತಮಾನದ ಸೂರ್ಯ ದೇವಾಲಯ।',
      or: 'ଭାରତର ଓଡ଼ିଶାର କୋଣାର୍କରେ ଥିବା ୧୩ଶ ଶତାବ୍ଦୀର ସୂର୍ଯ୍ୟ ମନ୍ଦିର।',
    },
    longDescription: {
      en: 'The Konark Sun Temple, a monumental marvel on the coastline of Odisha, is a 13th-century temple dedicated to the Hindu sun god, Surya. Conceived as a gigantic stone chariot for the deity, it features 24 intricately carved wheels and is drawn by a team of seven horses. This UNESCO World Heritage Site is a classic example of Kalinga architecture and is renowned for its elaborate and detailed stone carvings that cover every surface. These carvings depict a wide range of subjects, including deities, celestial beings, dancers, scenes of courtly life, and kama (sensual) figures. Although much of the temple is now in ruins, its surviving structures, particularly the massive wheels and the audience hall (Jagamohana), continue to attract visitors from around the world, standing as a testament to the boundless creativity and engineering genius of its builders.',
      hi: 'ओडिशा के समुद्र तट पर स्थित एक स्मारकीय चमत्कार, कोणार्क सूर्य मंदिर, 13वीं शताब्दी का एक मंदिर है जो हिंदू सूर्य देव, सूर्य को समर्पित है। देवता के लिए एक विशाल पत्थर के रथ के रूप में कल्पना की गई, इसमें 24 जटिल रूप से नक्काशीदार पहिये हैं और इसे सात घोड़ों की एक टीम द्वारा खींचा जाता है। यह यूनेस्को विश्व धरोहर स्थल कलिंग वास्तुकला का एक उत्कृष्ट उदाहरण है और अपनी विस्तृत और विस्तृत पत्थर की नक्काशी के लिए प्रसिद्ध है जो हर सतह को कवर करती है। इन नक्काशी में देवताओं, खगोलीय प्राणियों, नर्तकियों, दरबारी जीवन के दृश्यों और काम (कामुक) आकृतियों सहित विषयों की एक विस्तृत श्रृंखला को दर्शाया गया है। यद्यपि मंदिर का अधिकांश भाग अब खंडहर हो चुका है, इसकी जीवित संरचनाएं, विशेष रूप से विशाल पहिये और दर्शक हॉल (जगमोहन), दुनिया भर के आगंतुकों को आकर्षित करना जारी रखते हैं, जो इसके निर्माताओं की असीम रचनात्मकता और इंजीनियरिंग प्रतिभा के प्रमाण के रूप में खड़े हैं।',
      kn: 'ಒಡಿಶಾದ ಕರಾವಳಿಯಲ್ಲಿರುವ ಒಂದು ಸ್ಮಾರಕ ಅದ್ಭುತವಾದ ಕೋನಾರ್ಕ್ ಸೂರ್ಯ ದೇವಾಲಯವು 13 ನೇ ಶತಮಾನದ ದೇವಾಲಯವಾಗಿದ್ದು, ಹಿಂದೂ ಸೂರ್ಯ ದೇವರಾದ ಸೂರ್ಯನಿಗೆ ಸಮರ್ಪಿಸಲಾಗಿದೆ. ದೇವತೆಗಾಗಿ ದೈತ್ಯಾಕಾರದ ಕಲ್ಲಿನ ರಥವಾಗಿ ಕಲ್ಪಿಸಲಾಗಿದೆ, ಇದು 24 ಸಂಕೀರ್ಣವಾಗಿ ಕೆತ್ತಿದ ಚಕ್ರಗಳನ್ನು ಹೊಂದಿದೆ ಮತ್ತು ಏಳು ಕುದುರೆಗಳ ತಂಡದಿಂದ ಎಳೆಯಲಾಗುತ್ತದೆ. ಈ ಯುನೆಸ್ಕೋ ವಿಶ್ವ ಪರಂಪರೆಯ ತಾಣವು ಕಳಿಂಗ ವಾಸ್ತುಶಿಲ್ಪದ ಒಂದು ಶ್ರೇಷ್ಠ ಉದಾಹರಣೆಯಾಗಿದೆ ಮತ್ತು ಪ್ರತಿ ಮೇಲ್ಮೈಯನ್ನು ಆವರಿಸುವ ಅದರ ವಿಸ್ತಾರವಾದ ಮತ್ತು ವಿವರವಾದ ಕಲ್ಲಿನ ಕೆತ್ತನೆಗಳಿಗೆ ಹೆಸರುವಾಸಿಯಾಗಿದೆ. ಈ ಕೆತ್ತನೆಗಳು ದೇವತೆಗಳು, ಆಕಾಶ ಜೀವಿಗಳು, ನರ್ತಕರು, ಆಸ್ಥಾನಿಕ ಜೀವನದ ದೃಶ್ಯಗಳು ಮತ್ತು ಕಾಮ (ಇಂದ್ರಿಯ) ವ್ಯಕ್ತಿಗಳು ಸೇರಿದಂತೆ ವ್ಯಾಪಕ ಶ್ರೇಣಿಯ ವಿಷಯಗಳನ್ನು ಚಿತ್ರಿಸುತ್ತವೆ. ದೇವಾಲಯದ ಹೆಚ್ಚಿನ ಭಾಗವು ಈಗ ಅವಶೇಷಗಳಾಗಿದ್ದರೂ, ಅದರ ಉಳಿದಿರುವ ರಚನೆಗಳು, ವಿಶೇಷವಾಗಿ ಬೃಹತ್ ಚಕ್ರಗಳು ಮತ್ತು ಪ್ರೇಕ್ಷಕರ ಸಭಾಂಗಣ (ಜಗಮೋಹನ), ಪ್ರಪಂಚದಾದ್ಯಂತದ ಸಂದರ್ಶಕರನ್ನು ಆಕರ್ಷಿಸುತ್ತಲೇ ಇವೆ, ಇದು ಅದರ ನಿರ್ಮಾಪಕರ ಮಿತಿಯಿಲ್ಲದ ಸೃಜನಶೀಲತೆ ಮತ್ತು ಎಂಜಿನಿಯರಿಂಗ್ ಪ್ರತಿಭೆಗೆ ಸಾಕ್ಷಿಯಾಗಿದೆ.',
      or: 'ଓଡ଼ିଶାର ଉପକୂଳରେ ଥିବା ଏକ ସ୍ମାରକୀ ଚମତ୍କାର କୋଣାର୍କ ସୂର୍ଯ୍ୟ ମନ୍ଦିର, ୧୩ଶ ଶତାବ୍ଦୀର ଏକ ମନ୍ଦିର ଯାହା ହିନ୍ଦୁ ସୂର୍ଯ୍ୟ ଦେବତା ସୂର୍ଯ୍ୟଙ୍କୁ ସମର୍ପିତ। ଦେବତାଙ୍କ ପାଇଁ ଏକ ବିଶାଳ ପଥର ରଥ ଭାବରେ ପରିକଳ୍ପିତ, ଏଥିରେ ୨୪ଟି ଜଟିଳ ଭାବରେ ଖୋଦିତ ଚକ ରହିଛି ଏବଂ ଏହାକୁ ସାତୋଟି ଘୋଡ଼ାର ଏକ ଦଳ ଟାଣିଥାଏ। ଏହି ୟୁନେସ୍କୋ ବିଶ୍ୱ ଐତିହ୍ୟ ସ୍ଥଳୀ କଳିଙ୍ଗ ସ୍ଥାପତ୍ୟର ଏକ ଶାସ୍ତ୍ରୀୟ ଉଦାହରଣ ଏବଂ ଏହାର ବିସ୍ତୃତ ଏବଂ ବିସ୍ତାରିତ ପଥର ଖୋଦେଇ ପାଇଁ ପ୍ରସିଦ୍ଧ ଯାହା ପ୍ରତ୍ୟେକ ପୃଷ୍ଠକୁ ଆଚ୍ଛାଦନ କରେ। ଏହି ଖୋଦେଇରେ ଦେବତା, ସ୍ୱର୍ଗୀୟ ଜୀବ, ନୃତ୍ୟଶିଳ୍ପୀ, ଦରବାରୀ ଜୀବନର ଦୃଶ୍ୟ, ଏବଂ କାମ (କାମୁକ) ଚିତ୍ର ସମେତ ବିଭିନ୍ନ ବିଷୟବସ୍ତୁ ଚିତ୍ରିତ ହୋଇଛି। ଯଦିଓ ମନ୍ଦିରର ଅଧିକାଂଶ ଭାଗ ବର୍ତ୍ତମାନ ଧ୍ୱଂସାବଶେଷରେ ପରିଣତ ହୋଇଛି, ଏହାର ବଞ୍ଚିଥିବା ସଂରଚନା, ବିଶେଷକରି ବିଶାଳ ଚକ ଏବଂ ଦର୍ଶକ ହଲ (ଜଗମୋହନ), ବିଶ୍ୱର ବିଭିନ୍ନ ସ୍ଥାନରୁ ପର୍ଯ୍ୟଟକମାନଙ୍କୁ ଆକର୍ଷିତ କରିବାରେ ଲାଗିଛି, ଯାହା ଏହାର ନିର୍ମାତାମାନଙ୍କର ଅସୀମ ସୃଜନଶୀଳତା ଏବଂ ଇଞ୍ଜିନିୟରିଂ ପ୍ରତିଭାର ପ୍ରମାଣ ଭାବରେ ଛିଡା ହୋଇଛି।',
    },
    thumbnailUrlId: 'konark-sun-temple-thumb',
    coverImageUrlId: 'konark-sun-temple-cover',
    lowPolyModelUrl: '/models/konark_low.glb',
    highPolyModelUrl: '/models/sun_temple.glb',
    fallback360UrlId: 'fallback-360-konark',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-4'),
    arLink: 'https://nizammhd.github.io/MobileAR/',
  },
  {
    id: 'site-6',
    title: {
      en: 'Rani-ki-Vav',
      hi: 'रानी की वाव',
      kn: 'ರಾಣಿ-ಕಿ-ವಾವ್',
      or: 'ରାଣୀ-କି-ଭାଭ',
    },
    shortDescription: {
      en: 'An intricately constructed stepwell situated in the town of Patan in Gujarat.',
      hi: 'गुजरात के पाटन में स्थित एक जटिल रूप से निर्मित सीढ़ीनुमा बावड़ी।',
      kn: 'ಗುಜರಾತಿನ ಪಾಟಣ ನಗರದೊಂದರಲ್ಲಿ ಸ್ಥಿತವಾಗಿರುವ ಸೂಕ್ಷ್ಮವಾಗಿ ನಿರ್ಮಿಸಲಾದ ಮೆಟ್ಟಿಲು ಬಾವಿ।',
      or: 'ଗୁଜରାଟର ପାଟଣ ସହରରେ ଅବସ୍ଥିତ ଏକ ଜଟିଳ ଭାବରେ ନିର୍ମିତ ପାହାଚକୂପ।',
    },
    longDescription: {
      en: 'Rani-ki-Vav, or the Queen\'s Stepwell, is an exceptional example of subterranean water architecture located in Patan, Gujarat. Built in the 11th century by Queen Udayamati in memory of her husband, King Bhimdev I, it is designed as an inverted temple, a unique concept that highlights the sanctity of water. The stepwell descends through seven levels of stairs, adorned with over 500 principal sculptures and a thousand minor ones. These panels feature religious, mythological, and secular imagery, referencing literary works and contemporary life. The intricate craftsmanship and the sheer scale of the structure are breathtaking, serving not just as a water source but as a spiritual and social space. It stands as a pinnacle of the Maru-Gurjara architectural style and is a UNESCO World Heritage Site.',
      hi: 'रानी की वाव, या रानी की बावड़ी, गुजरात के पाटन में स्थित भूमिगत जल वास्तुकला का एक असाधारण उदाहरण है। 11वीं शताब्दी में रानी उदयमती द्वारा अपने पति राजा भीमदेव प्रथम की स्मृति में निर्मित, इसे एक उल्टे मंदिर के रूप में डिजाइन किया गया है, जो पानी की पवित्रता को उजागर करने वाली एक अनूठी अवधारणा है। यह बावड़ी सात स्तरों की सीढ़ियों से नीचे उतरती है, जो 500 से अधिक प्रमुख मूर्तियों और एक हजार छोटी मूर्तियों से सुशोभित है। इन पैनलों में धार्मिक, पौराणिक और धर्मनिरपेक्ष कल्पना है, जो साहित्यिक कार्यों और समकालीन जीवन का संदर्भ देती है। जटिल शिल्प कौशल और संरचना का विशाल पैमाना लुभावना है, जो न केवल पानी के स्रोत के रूप में बल्कि एक आध्यात्मिक और सामाजिक स्थान के रूप में भी काम करता है। यह मारू-गुर्जर स्थापत्य शैली का एक शिखर है और एक यूनेस्को विश्व धरोहर स्थल है।',
      kn: 'ರಾಣಿ-ಕಿ-ವಾಂ, ಅಥವಾ ರಾಣಿಯ ಮೆಟ್ಟಿಲುಬಾವಿ, ಗುಜರಾತ್‌ನ ಪಟಾನ್‌ನಲ್ಲಿರುವ ಭೂಗತ ನೀರಿನ ವಾಸ್ತುಶಿಲ್ಪದ ಒಂದು ಅಸಾಧಾರಣ ಉದಾಹರಣೆಯಾಗಿದೆ. 11 ನೇ ಶತಮಾನದಲ್ಲಿ ರಾಣಿ ಉದಯಮತಿಯಿಂದ ತನ್ನ ಪತಿ ರಾಜ ಭೀಮದೇವ I ರ ಸ್ಮರಣಾರ್ಥವಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ, ಇದನ್ನು ತಲೆಕೆಳಗಾದ ದೇವಾಲಯವಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ, ಇದು ನೀರಿನ ಪಾವಿತ್ರ್ಯತೆಯನ್ನು ಎತ್ತಿ ತೋರಿಸುವ ಒಂದು ಅನನ್ಯ ಪರಿಕಲ್ಪನೆಯಾಗಿದೆ. ಮೆಟ್ಟಿಲುಬಾವಿಯು ಏಳು ಹಂತದ ಮೆಟ್ಟಿಲುಗಳ ಮೂಲಕ ಇಳಿಯುತ್ತದೆ, 500 ಕ್ಕೂ ಹೆಚ್ಚು ಪ್ರಮುಖ ಶಿಲ್ಪಗಳು ಮತ್ತು ಸಾವಿರಾರು ಸಣ್ಣ ಶಿಲ್ಪಗಳಿಂದ ಅಲಂಕರಿಸಲ್ಪಟ್ಟಿದೆ. ಈ ಫಲಕಗಳು ಧಾರ್ಮಿಕ, ಪೌರಾಣಿಕ ಮತ್ತು ಜಾತ್ಯತೀತ ಚಿತ್ರಣವನ್ನು ಒಳಗೊಂಡಿವೆ, ಸಾಹಿತ್ಯ ಕೃತಿಗಳು ಮತ್ತು ಸಮಕಾಲೀನ ಜೀವನವನ್ನು ಉಲ್ಲೇಖಿಸುತ್ತವೆ. ಸಂಕೀರ್ಣವಾದ ಕರಕುಶಲತೆ ಮತ್ತು ರಚನೆಯ ಸಂಪೂರ್ಣ ಪ್ರಮಾಣವು ಉಸಿರುಕಟ್ಟುವಂತಿದೆ, ಇದು ಕೇವಲ ನೀರಿನ ಮೂಲವಾಗಿ ಮಾತ್ರವಲ್ಲದೆ ಆಧ್ಯಾತ್ಮಿಕ ಮತ್ತು ಸಾಮಾಜಿಕ ಸ್ಥಳವಾಗಿಯೂ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ. ಇದು ಮಾರು-ಗುರ್ಜರ ವಾಸ್ತುಶಿಲ್ಪದ ಶೈಲಿಯ ಶಿಖರವಾಗಿದೆ ಮತ್ತು ಯುನೆಸ್ಕೋ ವಿಶ್ವ ಪರಂಪರೆಯ ತಾಣವಾಗಿದೆ.',
      or: 'ରାଣୀ-କି-ଭାଭ୍, ବା ରାଣୀଙ୍କ ପାହାଚକୂପ, ଗୁଜରାଟର ପାଟଣରେ ଅବସ୍ଥିତ ଭୂତଳ ଜଳ ସ୍ଥାପତ୍ୟର ଏକ ଅସାଧାରଣ ଉଦାହରଣ। ୧୧ଶ ଶତାବ୍ଦୀରେ ରାଣୀ ଉଦୟମତୀଙ୍କ ଦ୍ୱାରା ତାଙ୍କ ସ୍ୱାମୀ ରାଜା ଭୀମଦେବ ପ୍ରଥମଙ୍କ ସ୍ମୃତିରେ ନିର୍ମିତ, ଏହାକୁ ଏକ ଓଲଟା ମନ୍ଦିର ଭାବରେ ପରିକଳ୍ପନା କରାଯାଇଛି, ଯାହା ଜଳର ପବିତ୍ରତାକୁ ଦର୍ଶାଉଥିବା ଏକ ଅନନ୍ୟ ଧାରଣା। ଏହି ପାହାଚକୂପଟି ସାତୋଟି ସ୍ତରର ପାହାଚ ଦେଇ ତଳକୁ ଯାଇଛି, ଯାହା ୫୦୦ରୁ ଅଧିକ ମୁଖ୍ୟ ମୂର୍ତ୍ତି ଏବଂ ହଜାରେ ଛୋଟ ମୂର୍ତ୍ତିରେ ସୁସଜ୍ଜିତ। ଏହି ପ୍ୟାନେଲଗୁଡ଼ିକରେ ଧାର୍ମିକ, ପୌରାଣିକ ଏବଂ ଧର୍ମନିରପେକ୍ଷ ଚିତ୍ର ରହିଛି, ଯାହା ସାହିତ୍ୟିକ କାର୍ଯ୍ୟ ଏବଂ ସମକାଳୀନ ଜୀବନକୁ ସୂଚିତ କରେ। ଜଟିଳ କାରୁକାର୍ଯ୍ୟ ଏବଂ ସଂରଚନାର ବିଶାଳତା ଚମତ୍କାର, ଯାହା କେବଳ ଜଳ ଉତ୍ସ ଭାବରେ ନୁହେଁ ବରଂ ଏକ ଆଧ୍ୟାତ୍ମିକ ଏବଂ ସାମାଜିକ ସ୍ଥାନ ଭାବରେ ମଧ୍ୟ କାର୍ଯ୍ୟ କରେ। ଏହା ମାରୁ-ଗୁର୍ଜର ସ୍ଥାପତ୍ୟ ଶୈଳୀର ଏକ ଶିଖର ଏବଂ ଏକ ୟୁନେସ୍କୋ ବିଶ୍ୱ ଐତିହ୍ୟ ସ୍ଥଳୀ।',
    },
    thumbnailUrlId: 'rani-ki-vav-thumb',
    coverImageUrlId: 'rani-ki-vav-cover',
    lowPolyModelUrl: '/models/rani_ki_vav_low.glb',
    highPolyModelUrl: '/models/rani-ki-vav.glb',
    fallback360UrlId: 'fallback-360-rani-ki-vav',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-6'),
  },
  {
    id: 'site-7',
    title: {
      en: 'Charminar',
      hi: 'चारमीनार',
      kn: 'ಚಾರ್ಮಿನಾರ್',
      or: 'ଚାରମିନାର',
    },
    shortDescription: {
      en: 'A monument and mosque located in Hyderabad, Telangana, India.',
      hi: 'हैदराबाद, तेलंगाना में स्थित एक स्मारक और मस्जिद।',
      kn: 'ತೆಲಂಗಾಣದ ಹೈದರಾಬಾದ್‌ಸ್ಥCharಪಾಪದಲ್ಲಿರುವ ಸಂಕೇತ ಮತ್ತು ಮಸೀದಿ।',
      or: 'ଭାରତର ତେଲେଙ୍ଗାନାର ହାଇଦ୍ରାବାଦରେ ଅବସ୍ଥିତ ଏକ ସ୍ମାରକୀ ଏବଂ ମସଜିଦ।',
    },
    longDescription: {
      en: 'Constructed in 1591, the Charminar is a monumental square archway in Hyderabad that has become the city\'s global icon. Built by Muhammad Quli Qutb Shah, the fifth ruler of the Qutb Shahi dynasty, it was erected to commemorate the end of a deadly plague. The name, which translates to "Four Minarets," refers to its four grand arches and four soaring minarets. Each minaret is crowned by a bulbous dome and contains a spiral staircase of 149 steps leading to the top floor, which houses a mosque. The structure is a celebrated example of Indo-Islamic architecture, blending Persian influences with local traditions. Located in the heart of the bustling Laad Bazaar, the Charminar stands as a proud symbol of Hyderabad\'s rich history and cultural fusion.',
      hi: '1591 में निर्मित, चारमीनार हैदराबाद में एक स्मारकीय चौकोर तोरण है जो शहर का वैश्विक प्रतीक बन गया है। कुतुब शाही वंश के पांचवें शासक मुहम्मद कुली कुतुब शाह द्वारा निर्मित, इसे एक घातक प्लेग के अंत की स्मृति में बनवाया गया था। इसका नाम, जिसका अनुवाद "चार मीनारें" है, इसके चार भव्य मेहराबों और चार ऊंची मीनारों को संदर्भित करता है। प्रत्येक मीनार एक गोलाकार गुंबद से सुशोभित है और इसमें 149 सीढ़ियों की एक सर्पिल सीढ़ी है जो शीर्ष मंजिल तक जाती है, जिसमें एक मस्जिद है। यह संरचना भारत-इस्लामी वास्तुकला का एक प्रसिद्ध उदाहरण है, जो फारसी प्रभावों को स्थानीय परंपराओं के साथ मिलाती है। हलचल भरे लाड बाजार के केंद्र में स्थित, चारमीनार हैदराबाद के समृद्ध इतिहास और सांस्कृतिक संलयन के गौरवपूर्ण प्रतीक के रूप में खड़ा है।',
      kn: '1591 ರಲ್ಲಿ ನಿರ್ಮಿಸಲಾದ ಚಾರ್ಮಿನಾರ್ ಹೈದರಾಬಾದ್‌ನಲ್ಲಿರುವ ಒಂದು ಸ್ಮಾರಕ ಚೌಕಾಕಾರದ ಕಮಾನುಮಾರ್ಗವಾಗಿದ್ದು ಅದು ನಗರದ ಜಾಗತಿಕ ಸಂಕೇತವಾಗಿದೆ. ಕುತುಬ್ ಶಾಹಿ ರಾಜವಂಶದ ಐದನೇ ಆಡಳಿತಗಾರ ಮುಹಮ್ಮద్ ಕುಲಿ ಕುತುಬ್ ಷಾ ನಿರ್ಮಿಸಿದ, ಇದನ್ನು ಮಾರಣಾಂತಿಕ ಪ್ಲೇಗ್‌ನ ಅಂತ್ಯವನ್ನು ಸ್ಮರಿಸಲು ನಿರ್ಮಿಸಲಾಯಿತು. "ನಾಲ್ಕು ಮಿನಾರ್‌ಗಳು" ಎಂದು ಅನುವಾದಿಸುವ ಹೆಸರು, ಅದರ ನಾಲ್ಕು ದೊಡ್ಡ ಕಮಾನುಗಳು ಮತ್ತು ನಾಲ್ಕು ಎತ್ತರದ ಮಿನಾರ್‌ಗಳನ್ನು ಸೂಚಿಸುತ್ತದೆ. ಪ್ರತಿಯೊಂದು ಮಿನಾರ್ ಬಲ್ಬಸ್ ಗುಮ್ಮಟದಿಂದ ಕಿರೀಟವನ್ನು ಹೊಂದಿದೆ మరియు 149 ಮೆಟ್ಟಿಲುಗಳ ಸುರುಳಿಯಾಕಾರದ ಮೆಟ್ಟಿಲನ್ನು ಹೊಂದಿದೆ, ಇದು ಮೇಲಿನ ಮಹಡಿಗೆ ಕಾರಣವಾಗುತ್ತದೆ, ಇದರಲ್ಲಿ ಮಸೀದಿ ಇದೆ. ಈ ರಚನೆಯು ಇಂಡೋ-ಇಸ್ಲಾಮಿಕ್ ವಾಸ್ತುಶಿಲ್ಪದ ಪ್ರಸಿದ್ಧ ಉದಾಹರಣೆಯಾಗಿದೆ, ಇದು ಪರ್ಷಿಯನ್ ಪ್ರಭಾವವನ್ನು ಸ್ಥಳೀಯ ಸಂಪ್ರದಾಯಗಳೊಂದಿಗೆ ಬೆಸೆಯುತ್ತದೆ. ಗದ್ದಲದ ಲಾಡ್ ಬಜಾರ್‌ನ ಹೃದಯಭಾಗದಲ್ಲಿರುವ ಚಾರ್ಮಿನಾರ್ ಹೈದರಾಬಾದ್‌ನ ಶ್ರೀಮಂತ ಇತಿಹಾಸ ಮತ್ತು ಸಾಂಸ್ಕೃತಿಕ ಸಮ್ಮಿಳನದ ಹೆಮ್ಮೆಯ ಸಂಕೇತವಾಗಿ ನಿಂತಿದೆ.',
      or: '୧୫୯୧ ମସିହାରେ ନିର୍ମିତ, ଚାରମିନାର ହାଇଦ୍ରାବାଦର ଏକ ସ୍ମାରକୀ ବର୍ଗାକାର ତୋରଣ ଯାହା ସହରର ବିଶ୍ୱସ୍ତରୀୟ ପ୍ରତୀକ ପାଲଟିଛି। କୁତବ ଶାହୀ ରାଜବଂଶର ପଞ୍ଚମ ଶାସକ ମହମ୍ମଦ କୁଲି କୁତବ ଶାହଙ୍କ ଦ୍ୱାରା ନିର୍ମିତ, ଏହାକୁ ଏକ ମାରାତ୍ମକ ମହାମାରୀର ସମାପ୍ତିକୁ ସ୍ମରଣ କରିବା ପାଇଁ ସ୍ଥାପନ କରାଯାଇଥିଲା। ଏହାର ନାମ, ଯାହାର ଅନୁବାଦ "ଚାରି ମିନାର", ଏହାର ଚାରୋଟି ଭବ୍ୟ କମାଣ ଏବଂ ଚାରୋଟି ଉଚ୍ଚ ମିନାରକୁ ସୂଚିତ କରେ। ପ୍ରତ୍ୟେକ ମିନାର ଏକ ଗୋଲାକାର ଗମ୍ବୁଜରେ ମୁକୁଟ ପିନ୍ଧିଛି ଏବଂ ଏଥିରେ ୧୪୯ଟି ପାହାଚର ଏକ ସର୍ପିଳ ସିଡ଼ି ଅଛି ଯାହା ଉପର ମହଲାକୁ ଯାଏ, ଯେଉଁଠାରେ ଏକ ମସଜିଦ ଅଛି। ଏହି ସଂରଚନା ଇଣ୍ଡୋ-ଇସଲାମିକ ସ୍ଥାପତ୍ୟର ଏକ ପ୍ରସିଦ୍ଧ ଉଦାହରଣ, ଯାହା ପାର୍ସୀ ପ୍ରଭାବକୁ ସ୍ଥାନୀୟ ପରମ୍ପରା ସହିତ ମିଶ୍ରଣ କରେ। ଜନଗହଳିପୂର୍ଣ୍ଣ ଲାଡ ବଜାରର ହୃଦୟରେ ଅବସ୍ଥିତ, ଚାରମିନାର ହାଇଦ୍ରାବାଦର ସମୃଦ୍ଧ ଇତିହାସ ଏବଂ ସାଂସ୍କୃତିକ ମିଶ୍ରଣର ଏକ ଗର୍ବିତ ପ୍ରତୀକ ଭାବରେ ଛିଡା ହୋଇଛି।',
    },
    thumbnailUrlId: 'charminar-thumb',
    coverImageUrlId: 'charminar-cover',
    lowPolyModelUrl: '/models/charminar_low.glb',
    highPolyModelUrl: '/models/charminar_hyderabad.glb',
    fallback360UrlId: 'fallback-360-charminar',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-7'),
  },
  {
    id: 'site-8',
    title: {
      en: 'Jagannath Puri Temple',
      hi: 'जगन्नाथ पुरी मंदिर',
      kn: 'ಜಗನ್ನಾಥ ಪುರಿ ದೇವಾಲಯ',
      or: 'ଜଗନ୍ନାଥ ପୁରୀ ମନ୍ଦିର',
    },
    shortDescription: {
      en: 'An important Hindu temple dedicated to Jagannath, a form of Vishnu.',
      hi: 'विष्णु के रूप जगन्नाथ को समर्पित एक महत्वपूर्ण हिंदू मंदिर।',
      kn: 'ವಿष्णುವಿನ ಆ ರೂಪವಾದ ಜಗನ್ನಾಥಕ್ಕಾಗಿ ಸಮರ್ಪಿತ ಪ್ರಮುಖ ಹಿಂದೂ ದೇವಾಲಯ।',
      or: 'ବିଷ୍ଣୁଙ୍କର ଏକ ରୂପ ଜଗନ୍ନାଥଙ୍କୁ ସମର୍ପିତ ଏକ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ହିନ୍ଦୁ ମନ୍ଦିର।',
    },
    longDescription: {
      en: 'The Shri Jagannath Temple in Puri, Odisha, is one of the most revered Hindu pilgrimage sites in India, forming part of the Char Dham pilgrimages. Dedicated to Lord Jagannath, a form of Vishnu, the temple complex is a magnificent example of Kalinga architecture. Rebuilt in the 10th century by King Anantavarman Chodaganga Deva, it is famous for its unique deities: Jagannath, his brother Balabhadra, and sister Subhadra, whose idols are carved from sacred neem wood. The temple is renowned for its annual Ratha Yatra, or chariot festival, where the three deities are pulled on massive, elaborately decorated chariots. This vibrant festival attracts millions of devotees, making it a spectacular display of faith and culture. The temple\'s massive kitchen, said to be the largest in the world, miraculously cooks for thousands of devotees daily.',
      hi: 'ओडिशा के पुरी में स्थित श्री जगन्नाथ मंदिर, भारत के सबसे प्रतिष्ठित हिंदू तीर्थ स्थलों में से एक है, जो चार धाम तीर्थयात्राओं का हिस्सा है। भगवान जगन्नाथ, विष्णु के एक रूप, को समर्पित, यह मंदिर परिसर कलिंग वास्तुकला का एक शानदार उदाहरण है। 10वीं शताब्दी में राजा अनंतवर्मन चोडगंग देव द्वारा पुनर्निर्मित, यह अपने अद्वितीय देवताओं के लिए प्रसिद्ध है: जगन्नाथ, उनके भाई बलभद्र, और बहन सुभद्रा, जिनकी मूर्तियाँ पवित्र नीम की लकड़ी से उकेरी गई हैं। मंदिर अपने वार्षिक रथ यात्रा, या रथ उत्सव के लिए प्रसिद्ध है, जहाँ तीनों देवताओं को विशाल, विस्तृत रूप से सजाए गए रथों पर खींचा जाता है। यह जीवंत त्योहार लाखों भक्तों को आकर्षित करता है, जो इसे विश्वास और संस्कृति का एक शानदार प्रदर्शन बनाता है। मंदिर की विशाल रसोई, जिसे दुनिया की सबसे बड़ी रसोई कहा जाता है, चमत्कारिक रूप से रोजाना हजारों भक्तों के लिए भोजन पकाती है।',
      kn: 'ಒಡಿಶಾದ ಪುರಿಯಲ್ಲಿರುವ ಶ್ರೀ ಜಗನ್ನಾಥ ದೇವಾಲಯವು ಭಾರತದ ಅತ್ಯಂತ ಪೂಜ್ಯ ಹಿಂದೂ ಯಾತ್ರಾ ಸ್ಥಳಗಳಲ್ಲಿ ಒಂದಾಗಿದೆ, ಇದು ಚಾರ್ ಧಾಮ್ ಯಾತ್ರೆಗಳ ಭಾಗವಾಗಿದೆ. ವಿಷ್ಣುವಿನ ಒಂದು ರೂಪವಾದ ಜಗನ್ನಾಥನಿಗೆ ಸಮರ್ಪಿತವಾದ ಈ ದೇವಾಲಯ ಸಂಕೀರ್ಣವು ಕಳಿಂಗ ವಾಸ್ತುಶಿಲ್ಪದ ಭವ್ಯವಾದ ಉದಾಹರಣೆಯಾಗಿದೆ. 10 ನೇ ಶತಮಾನದಲ್ಲಿ ರಾಜ ಅನಂತವರ್ಮನ್ ಚೋಡಗಂಗ ದೇವರಿಂದ ಪುನರ್ನಿರ್ಮಿಸಲಾಯಿತು, ಇದು ತನ್ನ ವಿಶಿಷ್ಟ ದೇವತೆಗಳಿಗೆ ಹೆಸರುವಾಸಿಯಾಗಿದೆ: ಜಗನ್ನಾಥ, ಅವನ ಸಹೋದರ ಬಲಭದ್ರ మరియు ಸಹೋದರಿ ಸುಭದ್ರಾ, ಅವರ ವಿಗ್ರಹಗಳನ್ನು ಪವಿತ್ರ ಬೇವಿನ ಮರದಿಂದ ಕೆತ್ತಲಾಗಿದೆ. ದೇವಾಲಯವು ತನ್ನ ವಾರ್ಷಿಕ ರಥ ಯಾತ್ರೆ, ಅಥವಾ ರಥೋತ್ಸವಕ್ಕೆ ಹೆಸರುವಾಸಿಯಾಗಿದೆ, ಅಲ್ಲಿ ಮೂರು ದೇವತೆಗಳನ್ನು ಬೃಹತ್, ವಿಸ್ತಾರವಾಗಿ ಅಲಂಕರಿಸಿದ ರಥಗಳ ಮೇಲೆ ಎಳೆಯಲಾಗುತ್ತದೆ. ಈ ರೋಮಾಂಚಕ ಹಬ್ಬವು ಲಕ್ಷಾಂತರ ಭಕ್ತರನ್ನು ಆಕರ್ಷಿಸುತ್ತದೆ, ಇದು ನಂಬಿಕೆ ಮತ್ತು ಸಂಸ್ಕೃತಿಯ ಅದ್ಭುತ ಪ್ರದರ್ಶನವಾಗಿದೆ. ದೇವಾಲಯದ ಬೃಹತ್ ಅಡುಗೆಮನೆ, ವಿಶ್ವದಲ್ಲೇ ಅತಿ ದೊಡ್ಡದು ಎಂದು ಹೇಳಲಾಗುತ್ತದೆ, ಪ್ರತಿದಿನ ಸಾವಿರಾರು ಭಕ್ತರಿಗಾಗಿ ಅದ್ಭುತವಾಗಿ ಅಡುಗೆ ಮಾಡುತ್ತದೆ.',
      or: 'ଓଡ଼ିଶାର ପୁରୀରେ ଥିବା ଶ୍ରୀ ଜଗନ୍ନାଥ ମନ୍ଦିର ଭାରତର ସବୁଠାରୁ ପୂଜନୀୟ ହିନ୍ଦୁ ତୀର୍ଥସ୍ଥଳୀମାନଙ୍କ ମଧ୍ୟରୁ ଅନ୍ୟତମ, ଯାହା ଚାରି ଧାମ ତୀର୍ଥଯାତ୍ରାର ଏକ ଅଂଶ। ଭଗବାନ ଜଗନ୍ନାଥ, ବିଷ୍ଣୁଙ୍କର ଏକ ରୂପ, ଙ୍କୁ ସମର୍ପିତ ଏହି ମନ୍ଦିର ପରିସର କଳିଙ୍ଗ ସ୍ଥାପତ୍ୟର ଏକ ଭବ୍ୟ ଉଦାହରଣ। ୧୦ମ ଶତାବ୍ଦୀରେ ରାଜା ଅନନ୍ତବର୍ମନ ଚୋଡ଼ଗଙ୍ଗ ଦେବଙ୍କ ଦ୍ୱାରା ପୁନର୍ନିର୍ମିତ, ଏହା ଏହାର ଅନନ୍ୟ ଦେବତାଙ୍କ ପାଇଁ ପ୍ରସିଦ୍ଧ: ଜଗନ୍ନାଥ, ତାଙ୍କ ଭାଇ ବଳଭଦ୍ର, ଏବଂ ଭଉଣୀ ସୁଭଦ୍ରା, ଯାହାଙ୍କର ମୂର୍ତ୍ତି ପବିତ୍ର ନିମ୍ବ କାଠରୁ ଖୋଦିତ ହୋଇଛି। ମନ୍ଦିରଟି ଏହାର ବାର୍ଷିକ ରଥଯାତ୍ରା, ବା ରଥ ଉତ୍ସବ ପାଇଁ ପ୍ରସିଦ୍ଧ, ଯେଉଁଠାରେ ତିନି ଦେବତାଙ୍କୁ ବିଶାଳ, ସୁସଜ୍ଜିତ ରଥରେ ଟଣାଯାଏ। ଏହି ଜୀବନ୍ତ ଉତ୍ସବ ଲକ୍ଷ ଲକ୍ଷ ଭକ୍ତଙ୍କୁ ଆକର୍ଷିତ କରେ, ଯାହା ଏହାକୁ ବିଶ୍ୱାସ ଏବଂ ସଂସ୍କୃତିର ଏକ ଚମତ୍କାର ପ୍ରଦର୍ଶନ କରିଥାଏ। ମନ୍ଦିରର ବିଶାଳ ରୋଷେଇଘର, ଯାହାକୁ ବିଶ୍ୱର ସବୁଠାରୁ ବଡ଼ ବୋଲି କୁହାଯାଏ, ଚମତ୍କାର ଭାବରେ ପ୍ରତିଦିନ ହଜାର ହଜାର ଭକ୍ତଙ୍କ ପାଇଁ ରୋଷେଇ କରେ।',
    },
    thumbnailUrlId: 'jagannath-puri-thumb',
    coverImageUrlId: 'jagannath-puri-cover',
    lowPolyModelUrl: '/models/jagannath_puri_low.glb',
    highPolyModelUrl: '/models/jagannath_puri_temple_model.glb',
    fallback360UrlId: 'fallback-360-jagannath-puri',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-8'),
  },
  {
    id: 'site-9',
    title: {
      en: 'Ellora Caves',
      hi: 'एलोरा गुफाएं',
      kn: 'ಎಲ್ಲೋರಾ ಗುಹೆಗಳು',
      or: 'ଏଲୋରା ଗୁମ୍ଫା',
    },
    shortDescription: {
      en: 'A UNESCO World Heritage Site located in the Aurangabad district of Maharashtra.',
      hi: 'महाराष्ट्र के औरंगाबाद जिले में स्थित एक यूनेस्को विश्व धरोहर स्थल।',
      kn: 'ಮಹಾರಾಷ್ಟ್ರದ ಔರಂಗಾಬಾದ್ ಜಿಲ್ಲೆಯಲ್ಲಿರುವ ಯುನೆಸ್ಕೋ ವಿಶ್ವ ಪರಂಪರೆ ತಾಣ।',
      or: 'ମହାରାଷ୍ଟ୍ରର ଔରଙ୍ଗାବାଦ ଜିଲ୍ଲାରେ ଅବସ୍ଥିତ ଏକ ୟୁନେସ୍କୋ ବିଶ୍ୱ ଐତିହ୍ୟ ସ୍ଥଳୀ।',
    },
    longDescription: {
      en: 'The Ellora Caves in Maharashtra are one of the largest rock-cut monastery-temple cave complexes in the world and a UNESCO World Heritage Site. This remarkable site features over 100 caves, though only 34 are open to the public, showcasing a unique blend of Hindu, Buddhist, and Jain monuments built between 600–1000 CE. This religious harmony is a key feature of Ellora. The undisputed centerpiece is Cave 16, known as the Kailasa Temple, which represents the world\'s largest single monolithic rock excavation. Carved from top to bottom out of a single rock, this temple is a staggering feat of engineering and artistry dedicated to Lord Shiva. The caves serve as a testament to the artistic and religious tolerance that prevailed in ancient India, making it a site of immense historical and cultural importance.',
      hi: 'महाराष्ट्र में एलोरा की गुफाएँ दुनिया के सबसे बड़े रॉक-कट मठ-मंदिर गुफा परिसरों में से एक हैं और एक यूनेस्को विश्व धरोहर स्थल हैं। इस उल्लेखनीय स्थल में 100 से अधिक गुफाएँ हैं, हालाँकि केवल 34 ही जनता के लिए खुली हैं, जो 600-1000 ईस्वी के बीच निर्मित हिंदू, बौद्ध और जैन स्मारकों का एक अनूठा मिश्रण प्रदर्शित करती हैं। यह धार्मिक सद्भाव एलोरा की एक प्रमुख विशेषता है। निर्विवाद केंद्रबिंदु गुफा 16 है, जिसे कैलाश मंदिर के रूप में जाना जाता है, जो दुनिया की सबसे बड़ी एकल अखंड चट्टान की खुदाई का प्रतिनिधित्व करता है। एक ही चट्टान से ऊपर से नीचे तक उकेरा गया, यह मंदिर भगवान शिव को समर्पित इंजीनियरिंग और कलात्मकता का एक चौंका देने वाला कारनामा है। ये गुफाएँ प्राचीन भारत में प्रचलित कलात्मक और धार्मिक सहिष्णुता का प्रमाण हैं, जो इसे अत्यधिक ऐतिहासिक और सांस्कृतिक महत्व का स्थल बनाती हैं।',
      kn: 'ಮಹಾರಾಷ್ಟ್ರದ ಎಲ್ಲೋರಾ ಗುಹೆಗಳು ವಿಶ್ವದ ಅತಿದೊಡ್ಡ ರಾಕ್-ಕಟ್ ಮಠ-ದೇವಾಲಯ ಗುಹೆ ಸಂಕೀರ್ಣಗಳಲ್ಲಿ ಒಂದಾಗಿದೆ ಮತ್ತು ಯುನೆಸ್ಕೋ ವಿಶ್ವ ಪರಂಪರೆಯ ತಾಣವಾಗಿದೆ. ಈ ಗಮನಾರ್ಹ ಸ್ಥಳವು 100 ಕ್ಕೂ ಹೆಚ್ಚು ಗುಹೆಗಳನ್ನು ಹೊಂದಿದೆ, ಆದರೂ ಸಾರ್ವಜನಿಕರಿಗೆ ಕೇವಲ 34 ಮಾತ್ರ ತೆರೆದಿರುತ್ತದೆ, ಇದು 600-1000 CE ನಡುವೆ ನಿರ್ಮಿಸಲಾದ ಹಿಂದೂ, ಬೌದ್ಧ ಮತ್ತು ಜೈನ ಸ್ಮಾರಕಗಳ ವಿಶಿಷ್ಟ ಮಿಶ್ರಣವನ್ನು ಪ್ರದರ್ಶಿಸುತ್ತದೆ. ಈ ಧಾರ್ಮಿಕ ಸಾಮರಸ್ಯವು ಎಲ್ಲೋರಾದ ಪ್ರಮುಖ ಲಕ್ಷಣವಾಗಿದೆ. ನಿರ್ವಿವಾದದ ಕೇಂದ್ರಭಾಗವೆಂದರೆ ಗುಹೆ 16, ಇದನ್ನು ಕೈಲಾಸ ದೇವಾಲಯ ಎಂದು ಕರೆಯಲಾಗುತ್ತದೆ, ಇದು ವಿಶ್ವದ ಅತಿದೊಡ್ಡ ಏಕಶಿಲೆಯ ಬಂಡೆಯ ಉತ್ಖನನವನ್ನು ಪ್ರತಿನಿಧಿಸುತ್ತದೆ. ಒಂದೇ ಬಂಡೆಯಿಂದ ಮೇಲಿನಿಂದ ಕೆಳಕ್ಕೆ ಕೆತ್ತಲಾಗಿದೆ, ಈ ದೇವಾಲಯವು ಶಿವನಿಗೆ ಸಮರ್ಪಿತವಾದ ಎಂಜಿನಿಯರಿಂಗ್ ಮತ್ತು ಕಲಾತ್ಮಕತೆಯ ದಿಗ್ಭ್ರಮೆಗೊಳಿಸುವ ಸಾಧನೆಯಾಗಿದೆ. ఈ ಗುಹೆಗಳು ಪ್ರಾಚೀನ ಭಾರತದಲ್ಲಿ ಚಾಲ್ತಿಯಲ್ಲಿದ್ದ ಕಲಾತ್ಮಕ ಮತ್ತು ಧಾರ್ಮಿಕ ಸಹಿಷ್ಣುತೆಗೆ ಸಾಕ್ಷಿಯಾಗಿದೆ, ಇದು ಅಪಾರ ಐತಿಹಾಸಿಕ ಮತ್ತು ಸಾಂಸ್ಕೃತಿಕ ಪ್ರಾಮುಖ್ಯತೆಯ ತಾಣವಾಗಿದೆ.',
      or: 'ମହାରାଷ୍ଟ୍ରର ଏଲୋରା ଗୁମ୍ଫା ବିଶ୍ୱର ସବୁଠାରୁ ବଡ଼ ପଥର-କଟା ମଠ-ମନ୍ଦିର ଗୁମ୍ଫା କମ୍ପ୍ଲେକ୍ସ ମଧ୍ୟରୁ ଗୋଟିଏ ଏବଂ ଏକ ୟୁନେସ୍କୋ ବିଶ୍ୱ ଐତିହ୍ୟ ସ୍ଥଳୀ। ଏହି ଉଲ୍ଲେଖନୀୟ ସ୍ଥାନରେ ୧୦୦ରୁ ଅଧିକ ଗୁମ୍ଫା ରହିଛି, ଯଦିଓ ସେଥିରୁ କେବଳ ୩୪ଟି ସର୍ବସାଧାରଣଙ୍କ ପାଇଁ ଖୋଲା, ଯାହା ୬୦୦–୧୦୦୦ ଖ୍ରୀଷ୍ଟାବ୍ଦ ମଧ୍ୟରେ ନିର୍ମିତ ହିନ୍ଦୁ, ବୌଦ୍ଧ ଏବଂ ଜୈନ ସ୍ମାରକୀର ଏକ ଅନନ୍ୟ ମିଶ୍ରଣ ପ୍ରଦର୍ଶନ କରେ। ଏହି ଧାର୍ମିକ ସଦ୍ଭାବ ଏଲୋରାର ଏକ ମୁଖ୍ୟ ବୈଶିଷ୍ଟ୍ୟ। ଏହାର ନିର୍ବିବାଦ କେନ୍ଦ୍ରବିନ୍ଦୁ ହେଉଛି ଗୁମ୍ଫା ୧୬, ଯାହାକୁ କୈଳାସ ମନ୍ଦିର କୁହାଯାଏ, ଯାହା ବିଶ୍ୱର ସବୁଠାରୁ ବଡ଼ ଏକକ ଏକଶିଳା ପଥର ଖନନକୁ ପ୍ରତିନିଧିତ୍ୱ କରେ। ଗୋଟିଏ ପଥରରୁ ଉପରୁ ତଳକୁ ଖୋଦିତ, ଏହି ମନ୍ଦିରଟି ଭଗବାନ ଶିବଙ୍କୁ ସମର୍ପିତ ଇଞ୍ଜିନିୟରିଂ ଏବଂ କଳାକାରିତାର ଏକ ଚମତ୍କାର କୃତି। ଏହି ଗୁମ୍ଫାଗୁଡ଼ିକ ପ୍ରାଚୀନ ଭାରତରେ ପ୍ରଚଳିତ କଳାତ୍ମକ ଏବଂ ଧାର୍ମିକ ସହିଷ୍ଣୁତାର ପ୍ରମାଣ ଭାବରେ କାର୍ଯ୍ୟ କରେ, ଯାହା ଏହାକୁ ଅତ୍ୟନ୍ତ ଐତିହାସିକ ଏବଂ ସାଂସ୍କୃତିକ ଗୁରୁତ୍ୱର ସ୍ଥାନ କରିଥାଏ।',
    },
    thumbnailUrlId: 'ellora-caves-thumb',
    coverImageUrlId: 'ellora-caves-cover',
    lowPolyModelUrl: '/models/ellora_caves_low.glb',
    highPolyModelUrl: '/models/ellora_caves__india.glb',
    fallback360UrlId: 'fallback-360-ellora-caves',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-9'),
  },
  {
    id: 'site-10',
    title: {
      en: 'Sanchi Stupa',
      hi: 'सांची स्तूप',
      kn: 'ಸಾಂಚಿ ಸ್ತೂಪ',
      or: 'ସାଞ୍ଚି ସ୍ତୂପ',
    },
    shortDescription: {
      en: 'A Buddhist complex, famous for its Great Stupa, on a hilltop at Sanchi Town in Madhya Pradesh.',
      hi: 'मध्य प्रदेश के सांची टाउन में एक पहाड़ी पर स्थित एक बौद्ध परिसर, जो अपने महान स्तूप के लिए प्रसिद्ध है।',
      kn: 'ಮಧ್ಯಪ್ರದೇಶದ ಸಾಂಚಿ ಪಟ್ಟಣದಲ್ಲಿ ಗುಡ್ಡಮೇಲಿನ ಮಹಾಸ್ತೂಪಕ್ಕಾಗಿ ಪ್ರಸಿದ್ಧವಾದ ಬೌದ್ಧ ಸಂಕೀರ್ಣ।',
      or: 'ମଧ୍ୟପ୍ରଦେଶର ସାଞ୍ଚି ସହରର ଏକ ପାହାଡ଼ ଉପରେ ଥିବା ଏକ ବୌଦ୍ଧ କମ୍ପ୍ଲେକ୍ସ, ଯାହା ଏହାର ମହାନ ସ୍ତୂପ ପାଇଁ ପ୍ରସିଦ୍ଧ।',
    },
    longDescription: {
      en: 'The Great Stupa at Sanchi is one of India\'s oldest and most significant Buddhist monuments. Originally commissioned in the 3rd century BCE by the Mauryan Emperor Ashoka, its core was a simple hemispherical brick structure built over the relics of the Buddha. Over the centuries, it was expanded and embellished, most notably during the Shunga and Satavahana periods. The current structure is encased in stone and features four exquisitely carved gateways, or toranas, which were added in the 1st century BCE. These gateways are adorned with intricate narrative sculptures depicting scenes from the life of the Buddha and the Jataka tales. The stupa itself is a symbol of the Buddha\'s final release from the cycle of birth and rebirth (Parinirvana) and serves as a major center for Buddhist pilgrimage and art.',
      hi: 'सांची का महान स्तूप भारत के सबसे पुराने और सबसे महत्वपूर्ण बौद्ध स्मारकों में से एक है। मूल रूप से तीसरी शताब्दी ईसा पूर्व में मौर्य सम्राट अशोक द्वारा कमीशन किया गया, इसका मूल बुद्ध के अवशेषों पर निर्मित एक साधारण अर्धगोलाकार ईंट संरचना थी। सदियों से, इसका विस्तार और अलंकरण किया गया, विशेष रूप से शुंग और सातवाहन काल के दौरान। वर्तमान संरचना पत्थर में लिपटी हुई है और इसमें चार उत्कृष्ट नक्काशीदार प्रवेश द्वार, या तोरण हैं, जिन्हें पहली शताब्दी ईसा पूर्व में जोड़ा गया था। ये प्रवेश द्वार बुद्ध के जीवन और जातक कथाओं के दृश्यों को दर्शाने वाली जटिल कथात्मक मूर्तियों से सुशोभित हैं। स्तूप स्वयं बुद्ध की जन्म और पुनर्जन्म के चक्र से अंतिम मुक्ति (परिनिर्वाण) का प्रतीक है और बौद्ध तीर्थयात्रा और कला के लिए एक प्रमुख केंद्र के रूप में कार्य करता है।',
      kn: 'ಸಾಂಚಿಯಲ್ಲಿರುವ ಮಹಾ ಸ್ತೂಪವು ಭಾರತದ ಅತ್ಯಂತ ಹಳೆಯ ಮತ್ತು ಮಹತ್ವದ ಬೌದ್ಧ ಸ್ಮಾರಕಗಳಲ್ಲಿ ಒಂದಾಗಿದೆ. ಮೂಲತಃ ಕ್ರಿ.ಪೂ 3 ನೇ ಶತಮಾನದಲ್ಲಿ ಮೌರ್ಯ ಚಕ್ರವರ್ತಿ ಅಶೋಕರಿಂದ ನಿಯೋಜಿಸಲ್ಪಟ್ಟಿದೆ, ಅದರ ತಿರುಳು बुद्धನ ಅವಶೇಷಗಳ ಮೇಲೆ ನಿರ್ಮಿಸಲಾದ ಸರಳ ಅರ್ಧಗೋಳದ ಇಟ್ಟಿಗೆ ರಚನೆಯಾಗಿದೆ. ಶತಮಾನಗಳಿಂದ, ಇದನ್ನು ವಿಸ್ತರಿಸಲಾಯಿತು ಮತ್ತು ಅಲಂಕರಿಸಲಾಯಿತು, ವಿಶೇಷವಾಗಿ ಶುಂಗ ಮತ್ತು శాతవాహన ಅವಧಿಗಳಲ್ಲಿ. ಪ್ರಸ್ತುತ ರಚನೆಯನ್ನು ಕಲ್ಲಿನಲ್ಲಿ ಸುತ್ತುವರಿಯಲಾಗಿದೆ ಮತ್ತು ನಾಲ್ಕು ಸೊಗಸಾಗಿ ಕೆತ್ತಿದ ಗೇಟ್‌ವೇಗಳು, ಅಥವಾ ತೋರಣಗಳನ್ನು ಹೊಂದಿದೆ, ಇವುಗಳನ್ನು ಕ್ರಿ.ಪೂ 1 ನೇ ಶತಮಾನದಲ್ಲಿ ಸೇರಿಸಲಾಯಿತು. ಈ ಗೇಟ್‌ವೇಗಳನ್ನು बुद्धನ ಜೀವನ ಮತ್ತು ಜಾತಕ ಕಥೆಗಳ ದೃಶ್ಯಗಳನ್ನು ಚಿತ್ರಿಸುವ ಸಂಕೀರ್ಣವಾದ ನಿರೂಪಣಾ ಶಿಲ್ಪಗಳಿಂದ ಅಲಂಕರಿಸಲಾಗಿದೆ. ಸ್ತೂಪವು ಸ್ವತಃ बुद्धನ ಜನನ ಮತ್ತು ಪುನರ್ಜನ್ಮದ ಚಕ್ರದಿಂದ (ಪರಿನಿರ್ವಾಣ) ಅಂತಿಮ ಬಿಡುಗಡೆಯ ಸಂಕೇತವಾಗಿದೆ మరియు ಬೌದ್ಧ ತೀರ್ಥಯಾತ್ರೆ ಮತ್ತು ಕಲೆಗೆ ಪ್ರಮುಖ ಕೇಂದ್ರವಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ.',
      or: 'ସାଞ୍ଚିର ମହାନ ସ୍ତୂପ ଭାରତର ସର୍ବପୁରାତନ ଏବଂ ସବୁଠାରୁ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ବୌଦ୍ଧ ସ୍ମାରକୀମାନଙ୍କ ମଧ୍ୟରୁ ଅନ୍ୟତମ। ମୂଳତଃ ଖ୍ରୀଷ୍ଟପୂର୍ବ ୩ୟ ଶତାବ୍ଦୀରେ ମୌର୍ଯ୍ୟ ସମ୍ରାଟ ଅଶୋକଙ୍କ ଦ୍ୱାରା ନିର୍ମିତ, ଏହାର ମୂଳ ଭାଗ ବୁଦ୍ଧଙ୍କ ଅବଶେଷ ଉପରେ ନିର୍ମିତ ଏକ ସରଳ ଅର୍ଦ୍ଧଗୋଲାକାର ଇଟା ସଂରଚନା ଥିଲା। ଶତାବ୍ଦୀ ଧରି, ଏହାକୁ ବିସ୍ତାର ଏବଂ ସୁସଜ୍ଜିତ କରାଯାଇଥିଲା, ବିଶେଷକରି ଶୁଙ୍ଗ ଏବଂ ସାତବାହନ ସମୟରେ। ବର୍ତ୍ତମାନର ସଂରଚନା ପଥରରେ ଆବୃତ ଏବଂ ଏଥିରେ ଚାରୋଟି ଚମତ୍କାର ଖୋଦିତ ପ୍ରବେଶଦ୍ୱାର, ବା ତୋରଣ ଅଛି, ଯାହା ଖ୍ରୀଷ୍ଟପୂର୍ବ ୧ମ ଶତାବ୍ଦୀରେ ଯୋଡ଼ା ଯାଇଥିଲା। ଏହି ପ୍ରବେଶଦ୍ୱାରଗୁଡ଼ିକ ବୁଦ୍ଧଙ୍କ ଜୀବନ ଏବଂ ଜାତକ କାହାଣୀର ଦୃଶ୍ୟକୁ ଚିତ୍ରଣ କରୁଥିବା ଜଟିଳ କାହାଣୀ ମୂର୍ତ୍ତିରେ ସୁସଜ୍ଜିତ। ସ୍ତୂପ ନିଜେ ବୁଦ୍ଧଙ୍କ ଜନ୍ମ ଏବଂ ପୁନର୍ଜନ୍ମ ଚକ୍ରରୁ ଅନ୍ତିମ ମୁକ୍ତି (ପରିନିର୍ବାଣ)ର ପ୍ରତୀକ ଏବଂ ବୌଦ୍ଧ ତୀର୍ଥଯାତ୍ରା ଏବଂ କଳାର ଏକ ପ୍ରମୁଖ କେନ୍ଦ୍ର ଭାବରେ କାର୍ଯ୍ୟ କରେ।',
    },
    thumbnailUrlId: 'sanchi-stupa-thumb',
    coverImageUrlId: 'sanchi-stupa-cover',
    lowPolyModelUrl: '/models/sanchi_stupa_low.glb',
    highPolyModelUrl: '/models/great_stupa_in_sanchi.glb',
    fallback360UrlId: 'fallback-360-sanchi-stupa',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-10'),
  },
];

export const getSites = (): Site[] => allSites;

export const getSiteById = (id: string): Site | undefined => allSites.find((site) => site.id === id);

export const getArtifacts = (): Artifact[] => allArtifacts;

export const getArtifactById = (id: string): Artifact | undefined => allArtifacts.find((artifact) => artifact.id === id);
