
'use server';
/**
 * @fileOverview A flow for generating text-to-speech audio.
 *
 * - generateAudio - A function that handles the TTS process.
 * - TTSInput - The input type for the generateAudio function.
 * - TTSOutput - The return type for the generateAudio function.
 */

import { ai } from '@/ai/genkit';
import { googleAI } from '@genkit-ai/google-genai';
import { z } from 'zod';
import wav from 'wav';

const TTSInputSchema = z.object({
  text: z.string().describe('The text to be converted to speech.'),
  lang: z.string().describe('The language of the text (e.g., "en", "hi").'),
});
export type TTSInput = z.infer<typeof TTSInputSchema>;

const TTSOutputSchema = z.object({
  media: z
    .string()
    .describe(
      "The generated audio as a data URI. Expected format: 'data:audio/wav;base64,<encoded_data>'."
    ),
});
export type TTSOutput = z.infer<typeof TTSOutputSchema>;

// This is the exported function that the UI will call.
export async function generateAudio(input: TTSInput): Promise<TTSOutput> {
  return generateAudioFlow(input);
}

const generateAudioFlow = ai.defineFlow(
  {
    name: 'generateAudioFlow',
    inputSchema: TTSInputSchema,
    outputSchema: TTSOutputSchema,
  },
  async ({ text, lang }) => {
    // Map our app's language codes to Google's supported voice codes
    // A more robust implementation might fetch available voices dynamically
    // Using pre-built voices for simplicity. See: https://cloud.google.com/text-to-speech/docs/voices
    const voiceMap: Record<string, string> = {
        'en': 'en-US-Standard-C', // English (Female)
        'hi': 'hi-IN-Standard-A', // Hindi (Female)
        'kn': 'kn-IN-Standard-A', // Kannada (Female)
        'or': 'or-IN-Standard-A', // Odia (Female)
    };

    const { media } = await ai.generate({
      model: googleAI.model('gemini-2.5-flash-preview-tts'),
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            // The voiceName here is just a placeholder, as language-specific
            // voices are often chosen automatically based on text language.
            // For more control, one might map `lang` to specific voice names.
            prebuiltVoiceConfig: { voiceName: voiceMap[lang] || 'Algenib' },
          },
        },
      },
      prompt: text,
    });

    if (!media) {
      throw new Error('No audio media was generated by the model.');
    }
    
    // The model returns raw PCM audio data, which needs to be converted to a playable format like WAV.
    const audioBuffer = Buffer.from(
      media.url.substring(media.url.indexOf(',') + 1),
      'base64'
    );

    const wavBase64 = await toWav(audioBuffer);

    return {
      media: 'data:audio/wav;base64,' + wavBase64,
    };
  }
);


/**
 * Converts raw PCM audio data into a WAV file format encoded in Base64.
 * @param pcmData The raw PCM audio buffer.
 * @param channels Number of audio channels. Defaults to 1.
 * @param rate Sample rate in Hz. Defaults to 24000, a common rate for TTS.
 * @param sampleWidth The width of each audio sample in bytes. Defaults to 2 (for 16-bit audio).
 * @returns A promise that resolves to the Base64 encoded string of the WAV data.
 */
async function toWav(
  pcmData: Buffer,
  channels = 1,
  rate = 24000,
  sampleWidth = 2
): Promise<string> {
  return new Promise((resolve, reject) => {
    const writer = new wav.Writer({
      channels,
      sampleRate: rate,
      bitDepth: sampleWidth * 8,
    });

    let bufs: any[] = [];
    writer.on('error', reject);
    writer.on('data', function (d) {
      bufs.push(d);
    });
    writer.on('end', function () {
      resolve(Buffer.concat(bufs).toString('base64'));
    });

    writer.write(pcmData);
    writer.end();
  });
}
